-- 编辑器自动生成，请勿直接修改！
---@class provinceConfig
local provinceConfig = {
    isLocal      = false,
    provinceList ={
        {
            id           = 1,
            isOpen       = true,
            isOnline     = true,
            name         = "安徽省",
            shortName    = "安徽",
            gameName     = "AnHui",
            appName     = "DHAHQP",
            btnName      = "btnAnHui",
            popTag       = 0,
            popIcon     = "Public_Electorate_选中_蓝",
            modName      = "package.public.module.playmodeconfigs.anhui_config",
        }
        ,
        {
            id           = 2,
            isOpen       = true,
            isOnline     = true,
            name         = "广东省",
            shortName    = "广东",
            gameName     = "GuangDong",
            appName     = "DHGDQP",
            btnName      = "btnGuangDong",
            popTag       = 0,
            popIcon     = "Public_Electorate_选中_兰绿",
            modName      = "package.public.module.playmodeconfigs.guangdong_config",
        }
        ,
        {
            id           = 3,
            isOpen       = true,
            isOnline     = true,
            name         = "河南省",
            shortName    = "河南",
            gameName     = "HeNan",
            appName     = "DHZYQP",
            btnName      = "btnHeNan",
            popTag       = 0,
            popIcon     = "Public_Electorate_选中_橘",
            modName      = "package.public.module.playmodeconfigs.henan_config",
        }
        ,
        {
            id           = 4,
            isOpen       = true,
            isOnline     = true,
            name         = "江苏省",
            shortName    = "江苏",
            gameName     = "JiangSu",
            appName     = "DHJSQP",
            btnName      = "btnJiangSu",
            popTag       = 0,
            popIcon     = "Public_Electorate_选中_绿",
            modName      = "package.public.module.playmodeconfigs.jiangsu_config",
        }
        ,
        {
            id           = 5,
            isOpen       = false,
            isOnline     = false,
            name         = "陕西省",
            shortName    = "陕西",
            gameName     = "ShanXi1",
            appName     = "DHSXQP",
            btnName      = "btnShanXi1",
            popTag       = 0,
            popIcon     = "Public_Electorate_选中_蓝",
            modName      = "package.public.module.playmodeconfigs.shanxi1_config",
        }
        ,
        {
            id           = 6,
            isOpen       = true,
            isOnline     = true,
            name         = "云南省",
            shortName    = "云南",
            gameName     = "YunNan",
            appName     = "DHYNQP",
            btnName      = "btnYunNan",
            popTag       = 0,
            popIcon     = "Public_Electorate_选中_绿",
            modName      = "package.public.module.playmodeconfigs.yunnan_config",
        }
        ,
        {
            id           = 7,
            isOpen       = true,
            isOnline     = true,
            name         = "湖南省",
            shortName    = "湖南",
            gameName     = "HuNan",
            appName     = "DHHNQP",
            btnName      = "btnHuNan",
            popTag       = 0,
            popIcon     = "Public_Electorate_选中_蓝",
            modName      = "package.public.module.playmodeconfigs.hunan_config",
        }
        ,
        {
            id           = 8,
            isOpen       = false,
            isOnline     = false,
            name         = "贵州省",
            shortName    = "贵州",
            gameName     = "GuiZhou",
            appName     = "DHGZQP",
            btnName      = "btnGuiZhou",
            popTag       = 0,
            popIcon     = "Public_Electorate_选中_橘",
            modName      = "package.public.module.playmodeconfigs.guizhou_config",
        }
        ,
        {
            id           = 9,
            isOpen       = true,
            isOnline     = true,
            name         = "广西省",
            shortName    = "广西",
            gameName     = "GuangXi",
            appName     = "DHGXQP",
            btnName      = "btnGuangXi",
            popTag       = 0,
            popIcon     = "Public_Electorate_选中_绿",
            modName      = "package.public.module.playmodeconfigs.guangxi_config",
        }
        ,
        {
            id           = 10,
            isOpen       = true,
            isOnline     = true,
            name         = "湖北省",
            shortName    = "湖北",
            gameName     = "HuBei",
            appName     = "DHHUBEIQP",
            btnName      = "btnHuBei",
            popTag       = 0,
            popIcon     = "Public_Electorate_选中_绿",
            modName      = "package.public.module.playmodeconfigs.hubei_config",
        }
        ,
        {
            id           = 11,
            isOpen       = true,
            isOnline     = true,
            name         = "新疆省",
            shortName    = "新疆",
            gameName     = "XinJiang",
            appName     = "DHXJQP",
            btnName      = "btnXinJiang",
            popTag       = 0,
            popIcon     = "Public_Electorate_选中_橘",
            modName      = "package.public.module.playmodeconfigs.xinjiang_config",
        }
        ,
        {
            id           = 12,
            isOpen       = true,
            isOnline     = true,
            name         = "澳门省",
            shortName    = "澳门",
            gameName     = "AoMen",
            appName     = "DHAMQP",
            btnName      = "btnAoMen",
            popTag       = 0,
            popIcon     = "Public_Electorate_选中_橘",
            modName      = "package.public.module.playmodeconfigs.aomen_config",
        }
        ,
        {
            id           = 13,
            isOpen       = true,
            isOnline     = true,
            name         = "江西省",
            shortName    = "江西",
            gameName     = "JiangXi",
            appName     = "DHJXQP",
            btnName      = "btnJiangXi",
            popTag       = 0,
            popIcon     = "Public_Electorate_选中_绿",
            modName      = "package.public.module.playmodeconfigs.jiangxi_config",
        }
        ,
        {
            id           = 14,
            isOpen       = true,
            isOnline     = true,
            name         = "山西省",
            shortName    = "山西",
            gameName     = "ShanXi",
            appName     = "DHSHXQP",
            btnName      = "btnShanXi",
            popTag       = 0,
            popIcon     = "Public_Electorate_选中_绿",
            modName      = "package.public.module.playmodeconfigs.shanxi_config",
        }
        ,
        {
            id           = 15,
            isOpen       = false,
            isOnline     = false,
            name         = "甘肃省",
            shortName    = "甘肃",
            gameName     = "GanSu",
            appName     = "DHGSQP",
            btnName      = "btnGanSu",
            popTag       = 1,
            popIcon     = "Public_Electorate_选中_绿",
            modName      = "package.public.module.playmodeconfigs.gansu_config",
        }
        ,
        {
            id           = 16,
            isOpen       = true,
            isOnline     = true,
            name         = "四川省",
            shortName    = "四川",
            gameName     = "SiChuan",
            appName     = "DHSCQP",
            btnName      = "btnSiChuan",
            popTag       = 1,
            popIcon     = "Public_Electorate_选中_绿",
            modName      = "package.public.module.playmodeconfigs.sichuan_config",
        }
        ,
        {
            id           = 17,
            isOpen       = true,
            isOnline     = true,
            name         = "好彩",
            shortName    = "好彩",
            gameName     = "HAOCAI",
            appName     = "HAOCAI",
            btnName      = "btnHAOCAI",
            popTag       = 0,
            popIcon     = "",
            modName      = "package.public.module.playmodeconfigs.haocai_config",
        }
        ,
        {
            id           = 18,
            isOpen       = true,
            isOnline     = true,
            name         = "辽宁省",
            shortName    = "辽",
            gameName     = "LiaoNing",
            appName     = "DHLNQP",
            btnName      = "btnLiaoNing",
            popTag       = 0,
            popIcon     = "Public_Electorate_选中_蓝",
            modName      = "package.public.module.playmodeconfigs.liaoning_config",
        }

    }
}
return provinceConfig
