-- 编辑器自动生成，请勿直接修改！
local playModeConfig = {
    {
        id           = 1,
        name         = "大众玩法",
        isOpen       = true,
        showIndex    = 1,
        playModeList ={
            {
                img          = "Public_Electorate_按钮_图标_红中",
                headIcon     = "Main_入口_红中",
                hallName     = "红中麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "红中麻将",
                gameName     = "HZMJ",
                gameId       = 1,
                isOpen       = true,
                package      = "majiang",
                location     = 1,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "hzmj_v2",
                wanfaType    = "hzmj_v2",
                createName   = "DHAHQP_HZMJ_HZ",
                goldRoomName         = "红中麻将",
                cardTheame   = "0|0|1",
            },
            {
                img          = "Public_Electorate_按钮_图标_比鸡",
                headIcon     = "Main_入口_极速比鸡",
                hallName     = "欢乐比鸡",
                bg           = "BackgroundHongZhong",
                btnImg       = "BiJi_Main_入口_图标_",
                tag          = 3,
                name         = "欢乐比鸡",
                gameName     = "BIJI",
                gameId       = 2,
                isOpen       = false,
                package      = "biji",
                location     = 1,
                showIndex    = 2,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "0|1|2",
                createName   = "DHAHQP_BIJI_BJ",
                tips         = "欢乐比鸡|舒城比鸡|六人比鸡",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_极速跑得快",
                hallName     = "极速跑得快",
                bg           = "BackgroundHongZhong",
                btnImg       = "Public_Main_入口_图标_",
                tag          = 1,
                name         = "极速跑得快",
                gameName     = "RUNFAST",
                gameId       = 3,
                isOpen       = true,
                package      = "runfast",
                location     = 1,
                showIndex    = 3,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = true,
                playTypeName = "pdk_3",
                wanfaType    = "1|2",
                createName   = "DHAHQP_RUNFAST_RUNFAST",
                tips         = "安徽关牌|经典跑得快",
                goldRoomName         = "跑得快",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_拼十",
                hallName     = "极速牛仔",
                bg           = "BackgroundHongZhong",
                btnImg       = "Public_Main_入口_图标_",
                tag          = 3,
                name         = "极速牛仔",
                gameName     = "BULLFIGHT",
                gameId       = 4,
                isOpen       = false,
                package      = "cowboy",
                location     = 1,
                showIndex    = 4,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                playTypeName = "bullfight",
                wanfaType    = "0|1|2|3",
                createName   = "DHAHQP_BULLFIGHT_BF",
                tips         = "轮流坐庄|随机坐庄|看牌抢庄|炸金牛",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_飘三叶",
                hallName     = "欢乐掼蛋",
                bg           = "BackgroundHongZhong",
                btnImg       = "Public_Main_入口_图标_",
                tag          = 0,
                name         = "欢乐掼蛋",
                gameName     = "GUANDAN",
                gameId       = 5,
                isOpen       = true,
                package      = "guandan",
                location     = 1,
                showIndex    = 5,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "0|1",
                createName   = "DHAHQP_GUANDAN_GD",
                tips         = "团团转|经典玩法",
            },
            {
                img          = "Public_Electorate_按钮_图标_通用斗地主",
                headIcon     = "Main_入口_斗地主",
                hallName     = "斗地主",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 1,
                name         = "斗地主",
                gameName     = "DOUDIZHU",
                gameId       = 7,
                isOpen       = true,
                package      = "doudizhu",
                location     = 1,
                showIndex    = 6,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "0",
                createName   = "DHAHQP_DOUDIZHU_DOUDIZHU",
                tips         = "斗地主",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_飘三叶",
                hallName     = "飘三叶",
                bg           = "BackgroundHongZhong",
                btnImg       = "Public_Main_入口_图标_",
                tag          = 3,
                name         = "飘三叶",
                gameName     = "ZHAJINHUA",
                gameId       = 6,
                isOpen       = false,
                package      = "zhajinhua",
                location     = 1,
                showIndex    = 7,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "0",
                createName   = "DHAHQP_ZHAJINHUA_ZHAJINHUA",
                tips         = "飘三叶",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_扑克通用",
                hallName     = "逮狗腿",
                bg           = "BackgroundHongZhong",
                btnImg       = "Public_Main_入口_图标_",
                tag          = 0,
                name         = "逮狗腿",
                gameName     = "DAIGOUTUI",
                gameId       = 8,
                isOpen       = true,
                package      = "daigoutui",
                location     = 1,
                showIndex    = 8,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "0",
                createName   = "DHAHQP_DAIGOUTUI_DAIGOUTUI",
                tips         = "逮狗腿",
            },
            {
                img          = "Public_Electorate_按钮_图标_红中",
                headIcon     = "Main_入口_换换",
                hallName     = "换换麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "换换麻将",
                gameName     = "DZHH",
                gameId       = 9,
                isOpen       = true,
                package      = "majiang",
                location     = 1,
                showIndex    = 9,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "wbmj_huanhuan",
                wanfaType    = "wbmj_huanhuan",
                createName   = "DHAHQP_DZHH_HH",
                tips         = "换换",
                goldRoomName         = "换换麻将",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_飘三叶",
                hallName     = "十三张",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 3,
                name         = "十三张",
                gameName     = "SHISANZHANG",
                gameId       = 10,
                isOpen       = false,
                package      = "shisanzhang",
                location     = 1,
                showIndex    = 10,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "0",
                createName   = "DHAHQP_SHISANZHANG_SSZ",
            },
            {
                img          = "public/module/setplaymodedata/public_setplaymodedatapublic.atlas,更多玩法 叫家子",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatapublic.atlas,推荐玩法-叫家子",
                hallName     = "叫家子",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "叫家子",
                gameName     = "JIAOJIAZI",
                gameId       = 11,
                isOpen       = false,
                package      = "jiaojiazi",
                location     = 1,
                showIndex    = 11,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "1|2",
                createName   = "DHAHQP_JIAOJIAZI_JIAOJIAZI",
                tips         = "安庆三副|安庆二副",
            }
        },
    },
    {
        id           = 2,
        name         = "马鞍山市",
        isOpen       = true,
        showIndex    = 2,
        playModeList ={
            {
                img          = "MAS_Main_图标_含山麻将",
                headIcon     = "Main_入口_含山",
                hallName     = "马鞍山市",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "含山麻将",
                gameName     = "MASMJ",
                gameId       = 201,
                isOpen       = true,
                package      = "majiang",
                location     = 2,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "masmj_hanshan",
                wanfaType    = "masmj_hanshan",
                createName   = "DHAHQP_MASMJ_HS",
                goldRoomName         = "含山麻将",
                cardTheame   = "0|0|1",
            }
        },
    },
    {
        id           = 3,
        name         = "芜湖市",
        isOpen       = true,
        showIndex    = 3,
        playModeList ={
            {
                img          = "WuHu_Main_图标_无为",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedataanhui.atlas,安徽_芜湖_无为",
                hallName     = "芜湖市",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "无为麻将",
                gameName     = "WHMJ",
                gameId       = 301,
                isOpen       = true,
                package      = "majiang",
                location     = 3,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "whmj_wuwei",
                wanfaType    = "whmj_wuwei",
                createName   = "DHAHQP_WHMJ_WW",
                goldRoomName         = "无为麻将",
                cardTheame   = "0|0|1",
            },
            {
                img          = "WuHu_Main_图标_南陵麻将",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedataanhui.atlas,安徽_芜湖_南陵",
                hallName     = "芜湖市",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "南陵麻将",
                gameName     = "WHMJ",
                gameId       = 302,
                isOpen       = true,
                package      = "majiang",
                location     = 3,
                showIndex    = 2,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "whmj_nanling",
                wanfaType    = "whmj_nanling",
                createName   = "DHAHQP_WHMJ_NL",
                goldRoomName         = "南陵麻将",
                cardTheame   = "0|0|1",
            }
        },
    },
    {
        id           = 4,
        name         = "亳州市",
        isOpen       = true,
        showIndex    = 4,
        playModeList ={
            {
                img          = "HaoZhou_Main_图标_利辛麻将",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedataanhui.atlas,安徽_亳州_利辛",
                hallName     = "亳州市",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "利辛麻将",
                gameName     = "BZMJ",
                gameId       = 401,
                isOpen       = true,
                package      = "majiang",
                location     = 4,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "bzmj_lixin",
                wanfaType    = "bzmj_lixin",
                createName   = "DHAHQP_BZMJ_LX",
                goldRoomName         = "利辛麻将",
                cardTheame   = "0|0|1",
            },
            {
                img          = "HaoZhou_Main_图标_涡阳麻将",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedataanhui.atlas,安徽_亳州_涡阳",
                hallName     = "亳州市",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "涡阳麻将",
                gameName     = "BZMJ",
                gameId       = 402,
                isOpen       = true,
                package      = "majiang",
                location     = 4,
                showIndex    = 2,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "bzmj_guoyang",
                wanfaType    = "bzmj_guoyang",
                createName   = "DHAHQP_BZMJ_GY",
                goldRoomName         = "涡阳麻将",
                cardTheame   = "0|0|1",
            },
            {
                img          = "HaoZhou_Main_图标_蒙城麻将",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedataanhui.atlas,安徽_亳州_蒙城",
                hallName     = "亳州市",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "蒙城麻将",
                gameName     = "BZMJ",
                gameId       = 403,
                isOpen       = true,
                package      = "majiang",
                location     = 4,
                showIndex    = 3,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                playTypeName = "bzmj_mengcheng",
                wanfaType    = "bzmj_mengcheng",
                createName   = "DHAHQP_BZMJ_MC",
                goldRoomName         = "蒙城麻将",
                cardTheame   = "0|0|1",
            }
        },
    },
    {
        id           = 5,
        name         = "池州市",
        isOpen       = true,
        showIndex    = 5,
        playModeList ={
            {
                img          = "public/module/setplaymodedata/public_setplaymodedataanhui.atlas,安徽_池州_青阳平胡",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedataanhui.atlas,安徽_池州_青阳平胡_大",
                hallName     = "池州市",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "青阳平胡",
                gameName     = "CZMJ",
                gameId       = 501,
                isOpen       = true,
                package      = "majiang",
                location     = 5,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "czmj_qyph",
                wanfaType    = "czmj_qyph",
                createName   = "DHAHQP_CZMJ_QYPH",
                goldRoomName         = "青阳平胡",
                cardTheame   = "1|1|1",
            },
            {
                img          = "public/module/setplaymodedata/public_setplaymodedataanhui.atlas,安徽_池州_青阳辣子",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedataanhui.atlas,安徽_池州_青阳辣子_大",
                hallName     = "池州市",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "青阳辣子",
                gameName     = "CZMJ",
                gameId       = 502,
                isOpen       = true,
                package      = "majiang",
                location     = 5,
                showIndex    = 2,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "czmj_qylz",
                wanfaType    = "czmj_qylz",
                createName   = "DHAHQP_CZMJ_QYLZ",
                goldRoomName         = "青阳辣子",
                cardTheame   = "0|0|1",
            },
            {
                img          = "public/module/setplaymodedata/public_setplaymodedataanhui.atlas,JiangSu_Main_图标_东至",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedataanhui.atlas,东至麻将",
                hallName     = "东至麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 3,
                name         = "东至麻将",
                gameName     = "CZDZ",
                gameId       = 503,
                isOpen       = true,
                package      = "majiang",
                location     = 5,
                showIndex    = 3,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "czmj_dz",
                wanfaType    = "czmj_dz",
                createName   = "DHAHQP_CZDZ_DZ",
                goldRoomName         = "东至麻将",
                cardTheame   = "0|0|1",
            },
            {
                img          = "public/module/setplaymodedata/public_setplaymodedataanhui.atlas,安徽_池州_东至点炮",
                headIcon     = "Main_入口_通用玩法",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "东至点炮胡",
                gameName     = "CZDZDPH",
                gameId       = 504,
                isOpen       = true,
                package      = "majiang",
                location     = 5,
                showIndex    = 4,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "dhahqp_czdzdph",
                createName   = "DHAHQP_CZDZDPH_DZ",
                cardTheame   = "2|2|3",
            },
            {
                img          = "public/module/setplaymodedata/public_setplaymodedataanhui.atlas,DengZhou_Main_图标_辣子",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedataanhui.atlas,辣子",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "池州辣子",
                gameName     = "CZLZ",
                gameId       = 505,
                isOpen       = true,
                package      = "majiang",
                location     = 5,
                showIndex    = 5,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "czmj_czlz",
                createName   = "DHAHQP_CZLZ_LZ",
                cardTheame   = "0|0|1",
            },
            {
                img          = "Public_Electorate_按钮_图标_红中",
                headIcon     = "Main_入口_通用玩法",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "九华山平胡",
                gameName     = "JHSPH",
                gameId       = 506,
                isOpen       = true,
                package      = "majiang",
                location     = 5,
                showIndex    = 6,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "ahjhs_phmj",
                createName   = "DHAHQP_JHSPH_JHS",
                cardTheame   = "0|0|1",
            },
            {
                img          = "Public_Electorate_按钮_图标_红中",
                headIcon     = "Main_入口_通用玩法",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "庙前平胡",
                gameName     = "MQPH",
                gameId       = 507,
                isOpen       = true,
                package      = "majiang",
                location     = 5,
                showIndex    = 7,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "ahmq_phmj",
                createName   = "DHAHQP_MQPH_MQ",
                cardTheame   = "0|0|1",
            }
        },
    },
    {
        id           = 6,
        name         = "蚌埠市",
        isOpen       = true,
        showIndex    = 6,
        playModeList ={
            {
                img          = "BengBu_Main_图标_固镇",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedataanhui.atlas,安徽_蚌埠_固镇推倒胡",
                hallName     = "蚌埠市",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "固镇推倒胡",
                gameName     = "BBMJ",
                gameId       = 601,
                isOpen       = true,
                package      = "majiang",
                location     = 6,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "bbmj_gztdh",
                wanfaType    = "bbmj_gztdh",
                createName   = "DHAHQP_BBMJ_GZ",
                goldRoomName         = "固镇推倒胡",
                cardTheame   = "0|0|1",
            },
            {
                img          = "BengBu_Main_图标_五河",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedataanhui.atlas,安徽_蚌埠_五河推倒胡",
                hallName     = "蚌埠市",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "五河推倒胡",
                gameName     = "BBMJ",
                gameId       = 602,
                isOpen       = true,
                package      = "majiang",
                location     = 6,
                showIndex    = 2,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "bbmj_whtdh",
                wanfaType    = "bbmj_whtdh",
                createName   = "DHAHQP_BBMJ_WH",
                goldRoomName         = "五河推倒胡",
                cardTheame   = "0|0|1",
            },
            {
                img          = "public/module/setplaymodedata/public_setplaymodedataanhui.atlas,BengBu_Main_图标_蚌埠麻将",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedataanhui.atlas,Main_入口_蚌埠",
                hallName     = "蚌埠市",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "蚌埠麻将",
                gameName     = "BBBB",
                gameId       = 603,
                isOpen       = true,
                package      = "majiang",
                location     = 6,
                showIndex    = 3,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "bbmj_bbmj",
                wanfaType    = "bbmj_bbmj",
                createName   = "DHAHQP_BBBB_BB",
                goldRoomName         = "蚌埠麻将",
                cardTheame   = "1|1|2",
            },
            {
                img          = "public/module/setplaymodedata/public_setplaymodedataanhui.atlas,BengBu_Main_图标_怀远",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedataanhui.atlas,Main_入口_怀远",
                hallName     = "怀远推倒胡",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 3,
                name         = "怀远推倒胡",
                gameName     = "BBHY",
                gameId       = 604,
                isOpen       = true,
                package      = "majiang",
                location     = 6,
                showIndex    = 4,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "bbmj_gztdh",
                createName   = "DHAHQP_BBHY_HY",
                cardTheame   = "1|1|2",
            }
        },
    },
    {
        id           = 7,
        name         = "滁州市",
        isOpen       = true,
        showIndex    = 7,
        playModeList ={
            {
                img          = "ChuZhou_Main_图标_明光",
                headIcon     = "Main_入口_明光",
                hallName     = "滁州市",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "明光麻将",
                gameName     = "CHUZMJ",
                gameId       = 701,
                isOpen       = true,
                package      = "majiang",
                location     = 7,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "chuzmj_mgmj",
                wanfaType    = "chuzmj_mgmj",
                createName   = "DHAHQP_CHUZMJ_MG",
                goldRoomName         = "明光麻将",
                cardTheame   = "0|0|1",
            },
            {
                img          = "public/module/setplaymodedata/public_setplaymodedataanhui.atlas,ChuZhou_Main_图标_天长",
                headIcon     = "Main_入口_天长",
                hallName     = "天长麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "天长麻将",
                gameName     = "CZTC",
                gameId       = 702,
                isOpen       = true,
                package      = "majiang",
                location     = 7,
                showIndex    = 2,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "ahcz_tcmj",
                wanfaType    = "ahcz_tcmj",
                createName   = "DHAHQP_CZTC_TC",
                goldRoomName         = "天长麻将",
                cardTheame   = "1|1|2",
            }
        },
    },
    {
        id           = 8,
        name         = "六安市",
        isOpen       = true,
        showIndex    = 8,
        playModeList ={
            {
                img          = "LuAn_Main_图标_六安",
                headIcon     = "Main_入口_六安",
                hallName     = "六安麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 2,
                name         = "六安麻将",
                gameName     = "LAMJ",
                gameId       = 804,
                isOpen       = true,
                package      = "majiang",
                location     = 8,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "lamj_liuan",
                wanfaType    = "lamj_liuan",
                createName   = "DHAHQP_LAMJ_LA",
                goldRoomName         = "六安麻将",
                cardTheame   = "1|1|2",
            },
            {
                img          = "LuAn_Main_图标_霍邱麻将",
                headIcon     = "Main_入口_霍邱",
                hallName     = "霍邱麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "霍邱麻将",
                gameName     = "LAHQ",
                gameId       = 801,
                isOpen       = true,
                package      = "majiang",
                location     = 8,
                showIndex    = 2,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "lamj_huoqiu",
                wanfaType    = "lamj_huoqiu",
                createName   = "DHAHQP_LAHQ_HQ",
                goldRoomName         = "霍邱麻将",
            },
            {
                img          = "LuAn_Main_图标_舒城麻将",
                headIcon     = "Main_入口_舒城",
                hallName     = "舒城麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "舒城麻将",
                gameName     = "LASC",
                gameId       = 802,
                isOpen       = true,
                package      = "majiang",
                location     = 8,
                showIndex    = 3,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "lamj_shucheng",
                wanfaType    = "lamj_shucheng",
                createName   = "DHAHQP_LASC_SC",
                goldRoomName         = "舒城麻将",
            },
            {
                img          = "LuAn_Main_图标_金寨麻将",
                headIcon     = "Main_入口_金寨",
                hallName     = "金寨麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "金寨麻将",
                gameName     = "LAJZ",
                gameId       = 803,
                isOpen       = true,
                package      = "majiang",
                location     = 8,
                showIndex    = 4,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "lamj_jinzhai",
                wanfaType    = "lamj_jinzhai",
                createName   = "DHAHQP_LAJZ_JZ",
                goldRoomName         = "金寨麻将",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_扑克通用",
                hallName     = "逮狗腿",
                bg           = "BackgroundHongZhong",
                btnImg       = "Public_Main_入口_图标_",
                tag          = 1,
                name         = "逮狗腿",
                gameName     = "DAIGOUTUI",
                gameId       = 805,
                isOpen       = true,
                package      = "daigoutui",
                location     = 8,
                showIndex    = 5,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "0",
                createName   = "DHAHQP_DAIGOUTUI_DAIGOUTUI",
                tips         = "逮狗腿",
            },
            {
                img          = "public/module/setplaymodedata/public_setplaymodedataanhui.atlas,LuAn_Main_图标_霍山",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedataanhui.atlas,Main_入口_霍山",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "霍山麻将",
                gameName     = "LAHS",
                gameId       = 806,
                isOpen       = false,
                package      = "majiang",
                location     = 8,
                showIndex    = 6,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "lamj_huoshan",
                createName   = "DHAHQP_LAHS_HS",
            },
            {
                img          = "public/module/setplaymodedata/public_setplaymodedatapublic.atlas,Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatapublic.atlas,Main_入口_扑克通用",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "金寨80分",
                gameName     = "JINZHAI80",
                gameId       = 807,
                isOpen       = false,
                package      = "shengji",
                location     = 8,
                showIndex    = 7,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "1",
                createName   = "DHAHQP_JINZHAI80_JINZHAI80",
                tips         = "金寨80分",
            }
        },
    },
    {
        id           = 9,
        name         = "安庆市",
        isOpen       = true,
        showIndex    = 9,
        playModeList ={
            {
                img          = "AnQing_Main_图标_太湖麻将",
                headIcon     = "Main_入口_太湖",
                hallName     = "太湖麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 2,
                name         = "太湖麻将",
                gameName     = "WJMJ",
                gameId       = 906,
                isOpen       = true,
                package      = "majiang",
                location     = 9,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "aqmj_taihu",
                wanfaType    = "aqmj_taihu",
                createName   = "DHAHQP_WJMJ_TH",
                goldRoomName         = "太湖麻将",
                cardTheame   = "0|0|1",
            },
            {
                img          = "AnQing_Main_图标_望江正宗",
                headIcon     = "Main_入口_望江",
                hallName     = "望江正宗",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "望江正宗",
                gameName     = "AQWJ",
                gameId       = 901,
                isOpen       = true,
                package      = "majiang",
                location     = 9,
                showIndex    = 2,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "aqmj_wangjiang",
                wanfaType    = "aqmj_wangjiang",
                createName   = "DHAHQP_AQWJ_WJ",
                goldRoomName         = "望江正宗",
            },
            {
                img          = "AnQing_Main_图标_安庆正宗",
                headIcon     = "Main_入口_安庆",
                hallName     = "安庆正宗",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "安庆正宗",
                gameName     = "AQAQ",
                gameId       = 902,
                isOpen       = true,
                package      = "majiang",
                location     = 9,
                showIndex    = 3,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "aqmj_anqing",
                wanfaType    = "aqmj_anqing",
                createName   = "DHAHQP_AQAQ_AQ",
                goldRoomName         = "安庆正宗",
            },
            {
                img          = "AnQing_Main_图标_宿松麻将",
                headIcon     = "Main_入口_宿松",
                hallName     = "宿松麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "宿松麻将",
                gameName     = "AQSS",
                gameId       = 903,
                isOpen       = true,
                package      = "majiang",
                location     = 9,
                showIndex    = 4,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "aqmj_susong",
                wanfaType    = "aqmj_susong",
                createName   = "DHAHQP_AQSS_SS",
                goldRoomName         = "宿松麻将",
            },
            {
                img          = "AnQing_Main_图标_岳西麻将",
                headIcon     = "Main_入口_岳西",
                hallName     = "岳西麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "岳西麻将",
                gameName     = "AQYX",
                gameId       = 904,
                isOpen       = true,
                package      = "majiang",
                location     = 9,
                showIndex    = 5,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "aqmj_yuexi",
                wanfaType    = "aqmj_yuexi",
                createName   = "DHAHQP_AQYX_YX",
                goldRoomName         = "岳西麻将",
            },
            {
                img          = "AnQing_Main_图标_潜山麻将",
                headIcon     = "Main_入口_潜山",
                hallName     = "潜山麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "潜山麻将",
                gameName     = "AQQS",
                gameId       = 905,
                isOpen       = true,
                package      = "majiang",
                location     = 9,
                showIndex    = 6,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "aqmj_qianshan",
                wanfaType    = "aqmj_qianshan",
                createName   = "DHAHQP_AQQS_QS",
                goldRoomName         = "潜山麻将",
            },
            {
                img          = "public/module/setplaymodedata/public_setplaymodedataanhui.atlas,AnQing_Main_图标_怀宁",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedataanhui.atlas,Main_入口_怀宁",
                hallName     = "安庆市",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 3,
                name         = "怀宁麻将",
                gameName     = "AQHN",
                gameId       = 907,
                isOpen       = true,
                package      = "majiang",
                location     = 9,
                showIndex    = 7,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "ahaq_hn",
                createName   = "DHAHQP_AQHN_HN",
                cardTheame   = "1|1|2",
            }
        },
    },
    {
        id           = 10,
        name         = "阜阳市",
        isOpen       = true,
        showIndex    = 10,
        playModeList ={
            {
                img          = "FuYang_Main_图标_太和",
                headIcon     = "Main_入口_太和",
                hallName     = "太和麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 2,
                name         = "太和麻将",
                gameName     = "FYMJ",
                gameId       = 1004,
                isOpen       = true,
                package      = "majiang",
                location     = 10,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "fymj_taihe",
                wanfaType    = "fymj_taihe",
                createName   = "DHAHQP_FYMJ_TH",
                goldRoomName         = "太和麻将",
                cardTheame   = "0|0|1",
            },
            {
                img          = "FuYang_Main_图标_阜南",
                headIcon     = "Main_入口_阜南",
                hallName     = "阜南掰夹子",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 2,
                name         = "阜南掰夹子",
                gameName     = "FNBJZ",
                gameId       = 1003,
                isOpen       = true,
                package      = "majiang",
                location     = 10,
                showIndex    = 2,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "wbmj_fnbjz",
                wanfaType    = "wbmj_fnbjz",
                createName   = "DHAHQP_FNBJZ_BJZ",
                goldRoomName         = "阜南掰夹子",
            },
            {
                img          = "FuYang_Main_图标_阜南",
                headIcon     = "Main_入口_阜南",
                hallName     = "阜南三门胡",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 2,
                name         = "阜南三门胡",
                gameName     = "FNSMH",
                gameId       = 1005,
                isOpen       = true,
                package      = "majiang",
                location     = 10,
                showIndex    = 3,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "wbmj_fnsmh",
                wanfaType    = "wbmj_fnsmh",
                createName   = "DHAHQP_FNSMH_SMH",
                goldRoomName         = "阜南三门胡",
            },
            {
                img          = "FuYang_Main_图标_临泉",
                headIcon     = "Main_入口_临泉",
                hallName     = "临泉麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 2,
                name         = "临泉麻将",
                gameName     = "FYLQ",
                gameId       = 1001,
                isOpen       = true,
                package      = "majiang",
                location     = 10,
                showIndex    = 4,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "wbmj_fuyang",
                wanfaType    = "wbmj_fuyang",
                createName   = "DHAHQP_FYLQ_LQ",
                goldRoomName         = "临泉麻将",
            },
            {
                img          = "FuYang_Main_图标_颍上",
                headIcon     = "Main_入口_颍上",
                hallName     = "颍上杠后翻",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "颍上杠后翻",
                gameName     = "WBYS",
                gameId       = 1002,
                isOpen       = true,
                package      = "majiang",
                location     = 10,
                showIndex    = 5,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "wbmj_yingshang",
                wanfaType    = "wbmj_yingshang",
                createName   = "DHAHQP_WBYS_YS",
                goldRoomName         = "颍上杠后翻",
            }
        },
    },
    {
        id           = 13,
        name         = "宿州市",
        isOpen       = true,
        showIndex    = 11,
        playModeList ={
            {
                img          = "SuZhou_Main_图标__萧县",
                headIcon     = "Main_入口_萧县",
                hallName     = "萧县麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "萧县麻将",
                gameName     = "SZMJXX",
                gameId       = 1301,
                isOpen       = true,
                package      = "majiang",
                location     = 13,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "szmj_xiaoxian",
                wanfaType    = "szmj_xiaoxian",
                createName   = "DHAHQP_SZMJXX_XX",
                goldRoomName         = "萧县麻将",
            },
            {
                img          = "SuZhou_Main_图标_图标_砀山",
                headIcon     = "Main_入口_砀山",
                hallName     = "宿州市",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "砀山麻将",
                gameName     = "SZDS",
                gameId       = 1302,
                isOpen       = true,
                package      = "majiang",
                location     = 13,
                showIndex    = 2,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "szds_dangshan",
                wanfaType    = "szds_dangshan",
                createName   = "DHAHQP_SZDS_DS",
                goldRoomName         = "砀山麻将",
                cardTheame   = "1|1|2",
            }
        },
    },
    {
        id           = 14,
        name         = "合肥市",
        isOpen       = true,
        showIndex    = 12,
        playModeList ={
            {
                img          = "HeFei_Main_图标_庐江",
                headIcon     = "Main_入口_庐江",
                hallName     = "合肥市",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "庐江麻将",
                gameName     = "HFLJ",
                gameId       = 1401,
                isOpen       = true,
                package      = "majiang",
                location     = 14,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "hfmj_lujiang",
                wanfaType    = "hfmj_lujiang",
                createName   = "DHAHQP_HFLJ_LJ",
                goldRoomName         = "庐江麻将",
            }
        },
    },
    {
        id           = 11,
        name         = "淮北市",
        isOpen       = true,
        showIndex    = 13,
        playModeList ={
            {
                img          = "HuaiBei_Main_图标_淮北",
                headIcon     = "Main_入口_淮北",
                hallName     = "淮北推到胡",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "淮北推到胡",
                gameName     = "WBHB",
                gameId       = 1101,
                isOpen       = true,
                package      = "majiang",
                location     = 11,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "wbmj_huaibei",
                wanfaType    = "wbmj_huaibei",
                createName   = "DHAHQP_WBHB_HB",
                goldRoomName         = "淮北推到胡",
            },
            {
                img          = "HuaiBei_Main_图标_濉溪",
                headIcon     = "Main_入口_渺溪",
                hallName     = "濉溪麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "濉溪麻将",
                gameName     = "WBSUIX",
                gameId       = 1102,
                isOpen       = true,
                package      = "majiang",
                location     = 11,
                showIndex    = 2,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "wbmj_suixi",
                wanfaType    = "wbmj_suixi",
                createName   = "DHAHQP_WBSUIX_SX",
                goldRoomName         = "濉溪麻将",
            }
        },
    },
    {
        id           = 12,
        name         = "淮南市",
        isOpen       = true,
        showIndex    = 14,
        playModeList ={
            {
                img          = "HuaiNan_Main_图标_淮南",
                headIcon     = "Main_入口_淮南",
                hallName     = "淮南麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "淮南麻将",
                gameName     = "WBHN",
                gameId       = 1201,
                isOpen       = true,
                package      = "majiang",
                location     = 12,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "wbmj_huainan",
                wanfaType    = "wbmj_huainan",
                createName   = "DHAHQP_WBHN_HN",
                goldRoomName         = "淮南麻将",
            },
            {
                img          = "HuaiNan_Main_图标_寿县",
                headIcon     = "Main_入口_寿县",
                hallName     = "寿县麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "寿县麻将",
                gameName     = "WBSX",
                gameId       = 1202,
                isOpen       = true,
                package      = "majiang",
                location     = 12,
                showIndex    = 2,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "wbmj_shouxian",
                wanfaType    = "wbmj_shouxian",
                createName   = "DHAHQP_WBSX_SX",
                goldRoomName         = "寿县麻将",
            },
            {
                img          = "HuaiNan_Main_图标_凤台",
                headIcon     = "Main_入口_凤台",
                hallName     = "凤台麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "凤台麻将",
                gameName     = "HNFTMJ",
                gameId       = 1203,
                isOpen       = true,
                package      = "majiang",
                location     = 12,
                showIndex    = 3,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "ahqp_hnft",
                wanfaType    = "ahqp_hnft",
                createName   = "DHAHQP_HNFTMJ_FT",
                goldRoomName         = "凤台麻将",
                cardTheame   = "1|1|2",
            },
            {
                img          = "public/module/setplaymodedata/public_setplaymodedataanhui.atlas,安徽_淮南_安丰麻将",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedataanhui.atlas,安丰麻将",
                hallName     = "淮南市",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 3,
                name         = "安丰麻将",
                gameName     = "HNAF",
                gameId       = 1204,
                isOpen       = true,
                package      = "majiang",
                location     = 12,
                showIndex    = 4,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "ahqp_hnaf",
                wanfaType    = "ahqp_hnaf",
                createName   = "DHAHQP_HNAF_AF",
                goldRoomName         = "安丰麻将",
                cardTheame   = "1|1|2",
            }
        },
    }
}
return playModeConfig
