-- 编辑器自动生成，请勿直接修改！
local playModeConfig = {
    {
        id           = 1,
        name         = "大众玩法",
        isOpen       = false,
        showIndex    = 1,
        playModeList ={
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_极速跑得快",
                hallName     = "跑得快",
                bg           = "BackgroundHongZhong",
                btnImg       = "Public_Main_入口_图标_",
                tag          = 1,
                name         = "跑得快",
                gameName     = "RUNFAST",
                gameId       = 1,
                isOpen       = true,
                package      = "runfast",
                location     = 1,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = true,
                playTypeName = "pdk_3",
                wanfaType    = "2",
                createName   = "DHAMQP_RUNFAST_RUNFAST",
                tips         = "经典玩法",
                goldRoomName         = "跑得快",
            },
            {
                img          = "Public_Electorate_按钮_图标_通用斗地主",
                headIcon     = "Main_入口_斗地主",
                hallName     = "斗地主",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 1,
                name         = "斗地主",
                gameName     = "DOUDIZHU",
                gameId       = 2,
                isOpen       = true,
                package      = "doudizhu",
                location     = 1,
                showIndex    = 2,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                playTypeName = "0",
                wanfaType    = "0",
                createName   = "DHAMQP_DOUDIZHU_DOUDIZHU",
                tips         = "斗地主",
                goldRoomName         = "斗地主",
            },
            {
                img          = "LuAn_Main_图标_六安",
                headIcon     = "Main_入口_六安",
                hallName     = "六安麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "六安麻将",
                gameName     = "LAMJ",
                gameId       = 3,
                isOpen       = true,
                package      = "majiang",
                location     = 1,
                showIndex    = 3,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                playTypeName = "lamj_liuan",
                wanfaType    = "lamj_liuan",
                createName   = "DHAMQP_LAMJ_LA",
                goldRoomName         = "六安麻将",
                cardTheame   = "1|1|2",
            },
            {
                img          = "LuAn_Main_图标_霍邱麻将",
                headIcon     = "Main_入口_霍邱",
                hallName     = "霍邱麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "霍邱麻将",
                gameName     = "LAHQ",
                gameId       = 4,
                isOpen       = true,
                package      = "majiang",
                location     = 1,
                showIndex    = 4,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                playTypeName = "lamj_huoqiu",
                wanfaType    = "lamj_huoqiu",
                createName   = "DHAMQP_LAHQ_HQ",
                goldRoomName         = "霍邱麻将",
            }
        },
    }
}
return playModeConfig
