-- 编辑器自动生成，请勿直接修改！
local playModeConfig = {
    {
        id           = 1,
        name         = "大众玩法",
        isOpen       = true,
        showIndex    = 1,
        playModeList ={
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_极速跑得快",
                hallName     = "跑得快",
                bg           = "BackgroundHongZhong",
                btnImg       = "Public_Main_入口_图标_",
                tag          = 1,
                name         = "跑得快",
                gameName     = "RUNFAST",
                gameId       = 1,
                isOpen       = true,
                package      = "runfast",
                location     = 1,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = true,
                playTypeName = "pdk_3",
                wanfaType    = "2",
                createName   = "DHGDQP_RUNFAST_RUNFAST",
                tips         = "跑得快",
                goldRoomName         = "跑得快",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_拼十",
                hallName     = "拼十",
                bg           = "BackgroundHongZhong",
                btnImg       = "Public_Main_入口_图标_",
                tag          = 3,
                name         = "拼十",
                gameName     = "BULLFIGHT",
                gameId       = 2,
                isOpen       = false,
                package      = "cowboy",
                location     = 1,
                showIndex    = 2,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                playTypeName = "bullfight",
                wanfaType    = "0|1|2",
                createName   = "DHGDQP_BULLFIGHT_BF",
                tips         = "经典拼十|看牌抢庄|通比拼十",
            },
            {
                img          = "Public_Electorate_按钮_图标_通用斗地主",
                headIcon     = "Main_入口_斗地主",
                hallName     = "斗地主",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 1,
                name         = "斗地主",
                gameName     = "DOUDIZHU",
                gameId       = 3,
                isOpen       = true,
                package      = "doudizhu",
                location     = 1,
                showIndex    = 3,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "0",
                createName   = "DHGDQP_DOUDIZHU_DOUDIZHU",
                tips         = "斗地主",
            }
        },
    },
    {
        id           = 2,
        name         = "普宁市",
        isOpen       = true,
        showIndex    = 2,
        playModeList ={
            {
                img          = "GuangDong_Main_图标_普宁",
                headIcon     = "Main_入口_普宁",
                hallName     = "普宁市",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "普宁逼胡",
                gameName     = "PNMJ",
                gameId       = 200,
                isOpen       = true,
                package      = "majiang",
                location     = 2,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "pnmj_puning",
                createName   = "DHGDQP_PNMJ_PN",
                cardTheame   = "1|1|2",
            },
            {
                img          = "GuangDong_Main_图标_普宁",
                headIcon     = "Main_入口_客家",
                hallName     = "普宁市",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "普宁客家",
                gameName     = "PNMJ",
                gameId       = 202,
                isOpen       = true,
                package      = "majiang",
                location     = 2,
                showIndex    = 2,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "pnmj_kejia",
                createName   = "DHGDQP_PNMJ_KJ",
                cardTheame   = "1|1|2",
            }
        },
    },
    {
        id           = 3,
        name         = "潮汕地区",
        isOpen       = true,
        showIndex    = 3,
        playModeList ={
            {
                img          = "GuangDong_Main_图标_潮汕麻将",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedataguangdong.atlas,潮汕麻将",
                hallName     = "潮汕麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "潮汕麻将",
                gameName     = "CSMJCS",
                gameId       = 301,
                isOpen       = true,
                package      = "majiang",
                location     = 3,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "gdmj_chaoshan",
                createName   = "DHGDQP_CSMJCS_CS",
                cardTheame   = "0|0|1",
            }
        },
    }
}
return playModeConfig
