-- 编辑器自动生成，请勿直接修改！
local playModeConfig = {
    {
        id           = 1,
        name         = "大众玩法",
        isOpen       = true,
        showIndex    = 1,
        playModeList ={
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_极速跑得快",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 1,
                name         = "跑得快",
                gameName     = "RUNFAST",
                gameId       = 1,
                isOpen       = true,
                package      = "runfast",
                location     = 1,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = true,
                playTypeName = "pdk_3",
                wanfaType    = "2",
                createName   = "HAOCAI_RUNFAST_RUNFAST",
                tips         = "跑得快",
                goldRoomName         = "跑得快",
            },
            {
                img          = "Public_Electorate_按钮_图标_通用斗地主",
                headIcon     = "Main_入口_斗地主",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 1,
                name         = "斗地主",
                gameName     = "DOUDIZHU",
                gameId       = 2,
                isOpen       = true,
                package      = "doudizhu",
                location     = 1,
                showIndex    = 2,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "0",
                createName   = "HAOCAI_DOUDIZHU_DOUDIZHU",
                tips         = "斗地主",
            },
            {
                img          = "Public_Electorate_按钮_图标_红中",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatapublic.atlas,Main_入口_极速跑得快",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "大理跑得快",
                gameName     = "RUNFASTDL",
                gameId       = 3,
                isOpen       = true,
                package      = "quickrun",
                location     = 1,
                showIndex    = 3,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                playTypeName = "pdk_3",
                wanfaType    = "2",
                createName   = "HAOCAI_RUNFASTDL_RUNFASTDL",
                tips         = "大理跑得快",
                goldRoomName         = "大理跑得快",
            },
            {
                img          = "Public_Electorate_按钮_图标_红中",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedataguangxi.atlas,北海推倒胡",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "大理推倒胡",
                gameName     = "DLTDH",
                gameId       = 4,
                isOpen       = true,
                package      = "majiang",
                location     = 1,
                showIndex    = 4,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "dlmj_tdh",
                createName   = "HAOCAI_DLTDH_TDH",
                cardTheame   = "1|1|2",
            },
            {
                img          = "Public_Electorate_按钮_图标_红中",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedataxinjiang.atlas,新疆血战到底",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "大理血战",
                gameName     = "DLXZDD",
                gameId       = 5,
                isOpen       = true,
                package      = "majiang",
                location     = 1,
                showIndex    = 5,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "dlmj_xzdd",
                createName   = "HAOCAI_DLXZDD_XZ",
                cardTheame   = "1|1|2",
            },
            {
                img          = "Public_Electorate_按钮_图标_红中",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatayunnan.atlas,Main_入口_飞小鸡",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "飞小鸡",
                gameName     = "QJMJFXJ",
                gameId       = 6,
                isOpen       = true,
                package      = "majiang",
                location     = 1,
                showIndex    = 6,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "ynqj_feixiaoji",
                wanfaType    = "ynqj_feixiaoji",
                createName   = "HAOCAI_QJMJFXJ_FXJ",
                goldRoomName         = "飞小鸡",
                cardTheame   = "1|1|2",
            }
        },
    }
}
return playModeConfig
