-- 编辑器自动生成，请勿直接修改！
local playModeConfig = {
    {
        id           = 1,
        name         = "大众玩法",
        isOpen       = true,
        showIndex    = 1,
        playModeList ={
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_极速跑得快",
                hallName     = "跑得快",
                bg           = "BackgroundHongZhong",
                btnImg       = "Public_Main_入口_图标_",
                tag          = 1,
                name         = "跑得快",
                gameName     = "RUNFAST",
                gameId       = 1,
                isOpen       = true,
                package      = "runfast",
                location     = 1,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = true,
                playTypeName = "pdk_3",
                wanfaType    = "2",
                createName   = "DHZYQP_RUNFAST_RUNFAST",
                tips         = "跑得快",
                goldRoomName         = "跑得快",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_拼十",
                hallName     = "拼十",
                bg           = "BackgroundHongZhong",
                btnImg       = "Public_Main_入口_图标_",
                tag          = 3,
                name         = "拼十",
                gameName     = "BULLFIGHT",
                gameId       = 2,
                isOpen       = false,
                package      = "cowboy",
                location     = 1,
                showIndex    = 2,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                playTypeName = "bullfight",
                wanfaType    = "0|1|2|3",
                createName   = "DHZYQP_BULLFIGHT_BF",
                tips         = "轮流坐庄|随机坐庄|看牌抢庄|炸金牛",
            },
            {
                img          = "Public_Electorate_按钮_图标_通用斗地主",
                headIcon     = "Main_入口_斗地主",
                hallName     = "斗地主",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 1,
                name         = "斗地主",
                gameName     = "DOUDIZHU",
                gameId       = 3,
                isOpen       = true,
                package      = "doudizhu",
                location     = 1,
                showIndex    = 3,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "0",
                createName   = "DHZYQP_DOUDIZHU_DOUDIZHU",
                tips         = "斗地主",
            }
        },
    },
    {
        id           = 2,
        name         = "邓州市",
        isOpen       = true,
        showIndex    = 2,
        playModeList ={
            {
                img          = "DengZhou_Main_图标_邓州麻将",
                headIcon     = "Main_入口_邓州",
                hallName     = "邓州市",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "邓州麻将",
                gameName     = "DZMJ",
                gameId       = 200,
                isOpen       = true,
                package      = "majiang",
                location     = 2,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "hnmj_dengzhou",
                wanfaType    = "hnmj_dengzhou",
                createName   = "DHZYQP_DZMJ_DZ",
                goldRoomName         = "邓州麻将",
                cardTheame   = "0|0|1",
            }
        },
    }
}
return playModeConfig
