-- 编辑器自动生成，请勿直接修改！
local playModeConfig = {
    {
        id           = 1,
        name         = "大众玩法",
        isOpen       = true,
        showIndex    = 1,
        playModeList ={
            {
                img          = "Public_Electorate_按钮_图标_红中",
                headIcon     = "Main_入口_红中",
                hallName     = "红中麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "红中麻将",
                gameName     = "HZMJ",
                gameId       = 1,
                isOpen       = false,
                package      = "majiang",
                location     = 1,
                showIndex    = 1,
                isOnline     = false,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "hzmj_v2",
                wanfaType    = "hzmj_v2",
                createName   = "DHHUBEIQP_HZMJ_HZ",
                goldRoomName         = "红中麻将",
                cardTheame   = "0|0|1",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_极速跑得快",
                hallName     = "跑得快",
                bg           = "BackgroundHongZhong",
                btnImg       = "Public_Main_入口_图标_",
                tag          = 1,
                name         = "跑得快",
                gameName     = "RUNFAST",
                gameId       = 3,
                isOpen       = true,
                package      = "runfast",
                location     = 1,
                showIndex    = 2,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = true,
                playTypeName = "pdk_3",
                wanfaType    = "2",
                createName   = "DHHUBEIQP_RUNFAST_RUNFAST",
                tips         = "跑得快",
                goldRoomName         = "跑得快",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_拼十",
                hallName     = "拼十",
                bg           = "BackgroundHongZhong",
                btnImg       = "Public_Main_入口_图标_",
                tag          = 3,
                name         = "拼十",
                gameName     = "BULLFIGHT",
                gameId       = 4,
                isOpen       = false,
                package      = "cowboy",
                location     = 1,
                showIndex    = 3,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                playTypeName = "bullfight",
                wanfaType    = "0|1|2|3",
                createName   = "DHHUBEIQP_BULLFIGHT_BF",
                tips         = "轮流坐庄|随机坐庄|看牌抢庄|炸金牛",
            },
            {
                img          = "HuBei_Main_图标_血流",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatapublic.atlas,血流成河",
                hallName     = "血流成河",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "血流成河",
                gameName     = "ZYXLCH",
                gameId       = 5,
                isOpen       = false,
                package      = "majiang",
                location     = 1,
                showIndex    = 4,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "hbzy_xueliu",
                wanfaType    = "hbzy_xueliu",
                createName   = "DHHUBEIQP_ZYXLCH_XL",
                goldRoomName         = "血流成河",
            },
            {
                img          = "HuBei_Main_图标_十卡五星",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatahubei.atlas,卡五星",
                hallName     = "极速卡五星",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "极速卡五星",
                gameName     = "KWX",
                gameId       = 6,
                isOpen       = true,
                package      = "majiang",
                location     = 1,
                showIndex    = 5,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "hbkwx_xiangyang|hbkwx_xiaogan|hbkwx_suizhou|hbkwx_shiyan",
                wanfaType    = "hbkwx_xiangyang|hbkwx_xiaogan|hbkwx_suizhou|hbkwx_shiyan",
                createName   = "DHHUBEIQP_KWX_XY|DHHUBEIQP_KWX_XG|DHHUBEIQP_KWX_SZ|DHHUBEIQP_KWX_SY",
                tips         = "襄阳卡五星|孝感卡五星|随州卡五星|十堰卡五星",
                goldRoomName         = "襄阳卡五星|孝感卡五星|随州卡五星|十堰卡五星",
            },
            {
                img          = "Public_Electorate_按钮_图标_通用斗地主",
                headIcon     = "Main_入口_斗地主",
                hallName     = "斗地主",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 1,
                name         = "斗地主",
                gameName     = "DOUDIZHU",
                gameId       = 7,
                isOpen       = true,
                package      = "doudizhu",
                location     = 1,
                showIndex    = 6,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "0",
                createName   = "DHHUBEIQP_DOUDIZHU_DOUDIZHU",
                tips         = "斗地主",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_飘三叶",
                hallName     = "飘三叶",
                bg           = "BackgroundHongZhong",
                btnImg       = "Public_Main_入口_图标_",
                tag          = 3,
                name         = "飘三叶",
                gameName     = "ZHAJINHUA",
                gameId       = 8,
                isOpen       = false,
                package      = "zhajinhua",
                location     = 1,
                showIndex    = 7,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "0",
                createName   = "DHHUBEIQP_ZHAJINHUA_ZHAJINHUA",
                tips         = "飘三叶",
            },
            {
                img          = "public/module/setplaymodedata/public_setplaymodedatahubei.atlas,HuBei_Main_图标_扑克510k",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatapublic.atlas,五十K",
                hallName     = "五十K",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "五十K",
                gameName     = "WUSHIK",
                gameId       = 9,
                isOpen       = true,
                package      = "wushik",
                location     = 1,
                showIndex    = 8,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "1|2|3|4",
                createName   = "DHHUBEIQP_WUSHIK_WUSHIK",
                tips         = "大冶玩法|黄石玩法|黄石经典|六人五十K",
            },
            {
                img          = "Public_Electorate_按钮_图标_红中",
                headIcon     = "Main_入口_通用玩法",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "大众血流成河",
                gameName     = "XLCH",
                gameId       = 10,
                isOpen       = false,
                package      = "majiang",
                location     = 1,
                showIndex    = 9,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "hbdz_xueliu",
                createName   = "DHHUBEIQP_DZXLCH_XL",
                cardTheame   = "1|1|2",
            },
            {
                img          = "public/module/setplaymodedata/public_setplaymodedatapublic.atlas,Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatapublic.atlas,Main_入口_扑克通用",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "浠水打七",
                gameName     = "DAQI",
                gameId       = 11,
                isOpen       = true,
                package      = "daqi",
                location     = 1,
                showIndex    = 10,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "1",
                createName   = "DHHUBEIQP_DAQI_DAQI",
                tips         = "浠水打七",
            }
        },
    },
    {
        id           = 2,
        name         = "大冶市",
        isOpen       = false,
        showIndex    = 2,
        playModeList ={
        },
    },
    {
        id           = 3,
        name         = "黄石市",
        isOpen       = true,
        showIndex    = 3,
        playModeList ={
            {
                img          = "HuBei_Main_图标_晃晃",
                headIcon     = "Main_入口_晃晃",
                hallName     = "黄石晃晃",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "黄石晃晃",
                gameName     = "HSHH",
                gameId       = 301,
                isOpen       = true,
                package      = "majiang",
                location     = 3,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "hubei_hshh",
                wanfaType    = "hubei_hshh",
                createName   = "DHHUBEIQP_HSHH_HH",
                goldRoomName         = "黄石晃晃",
                cardTheame   = "2|2|3",
            },
            {
                img          = "Public_Electorate_按钮_图标_字牌通用",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatahubei.atlas,大冶字牌",
                hallName     = "大冶字牌",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "大冶字牌",
                gameName     = "DYZP",
                gameId       = 302,
                isOpen       = true,
                package      = "huzi",
                location     = 3,
                showIndex    = 2,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "phz_hubei_dyzp",
                wanfaType    = "phz_hubei_dyzp",
                createName   = "DHHUBEIQP_DYZP_DY",
                goldRoomName         = "大冶字牌",
                cardTheame   = "2|2|3",
            },
            {
                img          = "public/module/setplaymodedata/public_setplaymodedatahubei.atlas,HuBei_Main_图标_开口番",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatahubei.atlas,开口番",
                hallName     = "开口番",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "开口番",
                gameName     = "DYKKF",
                gameId       = 303,
                isOpen       = true,
                package      = "majiang",
                location     = 3,
                showIndex    = 3,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "hubei_kkf",
                wanfaType    = "hubei_kkf",
                createName   = "DHHUBEIQP_DYKKF_KKF",
                goldRoomName         = "开口番",
                cardTheame   = "1|1|2",
            },
            {
                img          = "public/module/setplaymodedata/public_setplaymodedatahubei.atlas,Main_阳新",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatahubei.atlas,阳新",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "阳新麻将",
                gameName     = "HSYX",
                gameId       = 304,
                isOpen       = true,
                package      = "majiang",
                location     = 3,
                showIndex    = 4,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "hubei_hsyx",
                createName   = "DHHUBEIQP_HSYX_YX",
                cardTheame   = "2|2|3",
            }
        },
    },
    {
        id           = 4,
        name         = "恩施市",
        isOpen       = true,
        showIndex    = 4,
        playModeList ={
            {
                img          = "public/module/setplaymodedata/public_setplaymodedatahubei.atlas,花牌_选择玩法",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatahubei.atlas,恩施绍胡",
                hallName     = "恩施绍胡",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "恩施绍胡",
                gameName     = "ESSH",
                gameId       = 401,
                isOpen       = true,
                package      = "huapai",
                location     = 4,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "hp_essh",
                createName   = "DHHUBEIQP_ESSH_SH",
                cardTheame   = "2|2|3",
            },
            {
                img          = "public/module/setplaymodedata/public_setplaymodedatahubei.atlas,HuBei_Main_图标_恩施",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatahubei.atlas,恩施麻将",
                hallName     = "恩施麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "恩施麻将",
                gameName     = "ESMJ",
                gameId       = 402,
                isOpen       = true,
                package      = "majiang",
                location     = 4,
                showIndex    = 2,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "hbes_ypel|hbes_bpsl",
                wanfaType    = "hbes_ypel|hbes_bpsl",
                createName   = "DHHUBEIQP_ESMJ_YPEL|DHHUBEIQP_ESMJ_BPSL",
                tips         = "一痞二赖|八痞四赖",
                goldRoomName         = "一痞二赖|八痞四赖",
            },
            {
                img          = "public/module/setplaymodedata/public_setplaymodedatahubei.atlas,HuBei_Main_图标_利川",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatahubei.atlas,利川麻将",
                hallName     = "利川麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "利川麻将",
                gameName     = "ESLC",
                gameId       = 403,
                isOpen       = true,
                package      = "majiang",
                location     = 4,
                showIndex    = 3,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "hbmj_eslc",
                createName   = "DHHUBEIQP_ESLC_LC",
                cardTheame   = "1|1|2",
            }
        },
    },
    {
        id           = 5,
        name         = "黄冈市",
        isOpen       = true,
        showIndex    = 5,
        playModeList ={
            {
                img          = "public/module/setplaymodedata/public_setplaymodedatahubei.atlas,HuBei_Main_图标_浠水",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatahubei.atlas,浠水麻将",
                hallName     = "浠水麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "浠水麻将",
                gameName     = "HGXS",
                gameId       = 501,
                isOpen       = true,
                package      = "majiang",
                location     = 5,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "dhhg_xsmj",
                wanfaType    = "dhhg_xsmj",
                createName   = "DHHUBEIQP_HGXS_XS",
                goldRoomName         = "浠水麻将",
                cardTheame   = "2|2|3",
            },
            {
                img          = "public/module/setplaymodedata/public_setplaymodedatahubei.atlas,HuBei_Main_图标_罗田",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatahubei.atlas,罗田麻将",
                hallName     = "罗田麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "罗田麻将",
                gameName     = "HGLT",
                gameId       = 502,
                isOpen       = true,
                package      = "majiang",
                location     = 5,
                showIndex    = 2,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "hbmj_hglt",
                createName   = "DHHUBEIQP_HGLT_LT",
                cardTheame   = "2|0|2",
            }
        },
    },
    {
        id           = 6,
        name         = "宜昌市",
        isOpen       = true,
        showIndex    = 6,
        playModeList ={
            {
                img          = "public/module/setplaymodedata/public_setplaymodedatahubei.atlas,宜昌花牌_更多玩法",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatahubei.atlas,宜昌花牌_推荐图标",
                hallName     = "秭归上大人",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "秭归上大人",
                gameName     = "ZGHP",
                gameId       = 601,
                isOpen       = true,
                package      = "huazhipai",
                location     = 6,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "hp_zgsdr",
                createName   = "DHHUBEIQP_ZGHP_ZG",
                tips         = "秭归上大人",
                cardTheame   = "1|1|2",
            },
            {
                img          = "public/module/setplaymodedata/public_setplaymodedatahubei.atlas,宜昌花牌_更多玩法",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatahubei.atlas,宜昌花牌_推荐图标",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "远安翻精",
                gameName     = "YAHP",
                gameId       = 602,
                isOpen       = true,
                package      = "huazhipai",
                location     = 6,
                showIndex    = 2,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                playTypeName = "hp_yasdr",
                wanfaType    = "hp_yasdr|hp_yasdr_xl",
                createName   = "DHHUBEIQP_YAHP_YA",
                tips         = "远安翻精|远安血流",
                cardTheame   = "1|1|2",
            },
            {
                img          = "public/module/setplaymodedata/public_setplaymodedatahubei.atlas,宜昌花牌_更多玩法",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatahubei.atlas,宜昌花牌_推荐图标",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "兴山上大人",
                gameName     = "YCXSHP",
                gameId       = 603,
                isOpen       = true,
                package      = "huazhipai",
                location     = 6,
                showIndex    = 3,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "hp_xssdr",
                createName   = "DHHUBEIQP_YCXSHP_XS",
                tips         = "兴山上大人",
                cardTheame   = "1|1|2",
            },
            {
                img          = "public/module/setplaymodedata/public_setplaymodedatahubei.atlas,宜昌花牌_更多玩法",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatahubei.atlas,宜昌花牌_推荐图标",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "宜昌上大人",
                gameName     = "YCHP",
                gameId       = 604,
                isOpen       = true,
                package      = "huazhipai",
                location     = 6,
                showIndex    = 4,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "hp_ycsdr",
                createName   = "DHHUBEIQP_YCHP_YC",
                tips         = "宜昌上大人",
                cardTheame   = "1|1|2",
            },
            {
                img          = "public/module/setplaymodedata/public_setplaymodedatapublic.atlas,HuBei_Main_图标_血流",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatapublic.atlas,血流成河",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "宜昌血流",
                gameName     = "YCXLCH",
                gameId       = 605,
                isOpen       = true,
                package      = "majiang",
                location     = 6,
                showIndex    = 5,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "hbyc_xueliu",
                createName   = "DHHUBEIQP_YCXLCH_XL",
                cardTheame   = "1|1|2",
            },
            {
                img          = "public/module/setplaymodedata/public_setplaymodedatahubei.atlas,宜昌花牌_更多玩法",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatahubei.atlas,宜昌花牌_推荐图标",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "当阳翻精",
                gameName     = "YCDYHP",
                gameId       = 606,
                isOpen       = true,
                package      = "huazhipai",
                location     = 6,
                showIndex    = 6,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "hp_dysdr",
                createName   = "DHHUBEIQP_YCDYHP_DY",
                tips         = "当阳翻精",
                cardTheame   = "1|1|2",
            },
            {
                img          = "public/module/setplaymodedata/public_setplaymodedatahubei.atlas,宜昌花牌_更多玩法",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatahubei.atlas,宜昌花牌_推荐图标",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 3,
                name         = "宜昌三五精",
                gameName     = "YCSWJHP",
                gameId       = 607,
                isOpen       = true,
                package      = "huazhipai",
                location     = 6,
                showIndex    = 7,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "hp_swj_sj|hp_swj_wj",
                createName   = "DHHUBEIQP_YCSWJHP_SWJ",
                tips         = "三精花牌|五精花牌",
                cardTheame   = "1|1|2",
            }
        },
    },
    {
        id           = 7,
        name         = "鄂州市",
        isOpen       = true,
        showIndex    = 7,
        playModeList ={
            {
                img          = "public/module/setplaymodedata/public_setplaymodedatahubei.atlas,HuBei_Main_图标_晃晃",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatahubei.atlas,Main_入口_晃晃",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "鄂州晃晃",
                gameName     = "EZHH",
                gameId       = 701,
                isOpen       = true,
                package      = "majiang",
                location     = 7,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "hbmj_ezhh",
                wanfaType    = "hbmj_ezhh",
                createName   = "DHHUBEIQP_EZHH_HH",
                goldRoomName         = "鄂州晃晃",
                cardTheame   = "2|2|3",
            }
        },
    }
}
return playModeConfig
