-- 编辑器自动生成，请勿直接修改！
local playModeConfig = {
    {
        id           = 1,
        name         = "大众玩法",
        isOpen       = true,
        showIndex    = 1,
        playModeList ={
            {
                img          = "Public_Electorate_按钮_图标_红中",
                headIcon     = "Main_入口_红中",
                hallName     = "红中麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "红中麻将",
                gameName     = "HZMJ",
                gameId       = 5,
                isOpen       = true,
                package      = "majiang",
                location     = 1,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "hzmj_v2",
                createName   = "DHJSQP_HZMJ_HZ",
                cardTheame   = "0|0|1",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_极速跑得快",
                hallName     = "跑得快",
                bg           = "BackgroundHongZhong",
                btnImg       = "Public_Main_入口_图标_",
                tag          = 1,
                name         = "跑得快",
                gameName     = "RUNFAST",
                gameId       = 1,
                isOpen       = true,
                package      = "runfast",
                location     = 1,
                showIndex    = 2,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = true,
                playTypeName = "pdk_3",
                wanfaType    = "1|2",
                createName   = "DHJSQP_RUNFAST_RUNFAST",
                tips         = "江苏关牌|江苏跑得快",
                goldRoomName         = "跑得快",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_拼十",
                hallName     = "拼十",
                bg           = "BackgroundHongZhong",
                btnImg       = "Public_Main_入口_图标_",
                tag          = 0,
                name         = "拼十",
                gameName     = "BULLFIGHT",
                gameId       = 2,
                isOpen       = false,
                package      = "cowboy",
                location     = 1,
                showIndex    = 3,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                playTypeName = "bullfight",
                wanfaType    = "0|1|2|3",
                createName   = "DHJSQP_BULLFIGHT_BF",
                tips         = "轮流坐庄|随机坐庄|看牌抢庄|炸金牛",
            },
            {
                img          = "Public_Electorate_按钮_图标_比鸡",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatapublic.atlas,Main_入口_极速比鸡",
                hallName     = "江苏比鸡",
                bg           = "BackgroundBiJi",
                btnImg       = "BiJi_Main_入口_图标_",
                tag          = 3,
                name         = "江苏比鸡",
                gameName     = "BIJI",
                gameId       = 3,
                isOpen       = false,
                package      = "biji",
                location     = 1,
                showIndex    = 4,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "0|1",
                createName   = "DHJSQP_BIJI_BJ",
                tips         = "江苏比鸡",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_飘三叶",
                hallName     = "欢乐掼蛋",
                bg           = "BackgroundHongZhong",
                btnImg       = "Public_Main_入口_图标_",
                tag          = 0,
                name         = "欢乐掼蛋",
                gameName     = "GUANDAN",
                gameId       = 4,
                isOpen       = true,
                package      = "guandan",
                location     = 1,
                showIndex    = 5,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "0|1",
                createName   = "DHJSQP_GUANDAN_GD",
                tips         = "团团转|经典玩法",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_飘三叶",
                hallName     = "飘三叶",
                bg           = "BackgroundHongZhong",
                btnImg       = "Public_Main_入口_图标_",
                tag          = 0,
                name         = "飘三叶",
                gameName     = "ZHAJINHUA",
                gameId       = 6,
                isOpen       = false,
                package      = "zhajinhua",
                location     = 1,
                showIndex    = 6,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "0",
                createName   = "DHJSQP_ZHAJINHUA_ZHAJINHUA",
                tips         = "飘三叶",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_斗地主",
                hallName     = "五人斗地主",
                bg           = "BackgroundHongZhong",
                btnImg       = "Public_Main_入口_图标_",
                tag          = 1,
                name         = "五人斗地主",
                gameName     = "DAIGOUTUI",
                gameId       = 7,
                isOpen       = true,
                package      = "daigoutui",
                location     = 1,
                showIndex    = 7,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "0",
                createName   = "DHJSQP_DAIGOUTUI_DAIGOUTUI",
                tips         = "五人斗地主",
            },
            {
                img          = "Public_Electorate_按钮_图标_通用斗地主",
                headIcon     = "Main_入口_斗地主",
                hallName     = "三人斗地主",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 1,
                name         = "三人斗地主",
                gameName     = "DOUDIZHU",
                gameId       = 8,
                isOpen       = true,
                package      = "doudizhu",
                location     = 1,
                showIndex    = 8,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "0",
                createName   = "DHJSQP_DOUDIZHU_DOUDIZHU",
                tips         = "三人斗地主",
            }
        },
    },
    {
        id           = 2,
        name         = "连云港市",
        isOpen       = true,
        showIndex    = 2,
        playModeList ={
            {
                img          = "JiangSu_Main_图标_东海",
                headIcon     = "Main_入口_东海",
                hallName     = "东海麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "东海麻将",
                gameName     = "LYGMJ",
                gameId       = 201,
                isOpen       = true,
                package      = "majiang",
                location     = 2,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "jslyg_donghai",
                createName   = "DHJSQP_LYGMJ_DH",
                cardTheame   = "0|0|1",
            },
            {
                img          = "JiangSu_Main_图标_新浦",
                headIcon     = "Main_入口_新浦",
                hallName     = "新浦麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "新浦麻将",
                gameName     = "LYGMJXP",
                gameId       = 202,
                isOpen       = true,
                package      = "majiang",
                location     = 2,
                showIndex    = 2,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "jslyg_xinpu",
                createName   = "DHJSQP_LYGMJXP_XP",
                cardTheame   = "0|0|1",
            }
        },
    },
    {
        id           = 3,
        name         = "宿迁市",
        isOpen       = true,
        showIndex    = 3,
        playModeList ={
            {
                img          = "JiangSu_Main_图标_泗洪麻将",
                headIcon     = "Main_入口_泗洪",
                hallName     = "宿迁市",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "泗洪麻将",
                gameName     = "SQMJ",
                gameId       = 301,
                isOpen       = true,
                package      = "majiang",
                location     = 3,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "jssq_sihong",
                createName   = "DHJSQP_SQMJ_SH",
                cardTheame   = "0|0|1",
            }
        },
    },
    {
        id           = 4,
        name         = "南通市",
        isOpen       = true,
        showIndex    = 4,
        playModeList ={
            {
                img          = "Public_Electorate_按钮_图标_-长牌通用",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatajiangsu.atlas,南通长牌",
                hallName     = "南通市",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 1,
                name         = "南通长牌",
                gameName     = "NTCP",
                gameId       = 401,
                isOpen       = true,
                package      = "changpai",
                location     = 4,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "jsqp_nantong|jsqp_nantongdj",
                createName   = "DHJSQP_NTCP_NT",
                tips         = "南通长牌|单将长牌",
                cardTheame   = "0|0|1",
            },
            {
                img          = "Public_Electorate_按钮_图标_-长牌通用",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatajiangsu.atlas,海门长牌",
                hallName     = "南通市",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 3,
                name         = "海门长牌",
                gameName     = "HMCP",
                gameId       = 402,
                isOpen       = true,
                package      = "changpai",
                location     = 4,
                showIndex    = 2,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "jsqp_haimen",
                createName   = "DHJSQP_HMCP_HM",
                cardTheame   = "0|0|1",
            },
            {
                img          = "Public_Electorate_按钮_图标_-长牌通用",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatajiangsu.atlas,如东长牌",
                hallName     = "南通市",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 3,
                name         = "如东长牌",
                gameName     = "RDCP",
                gameId       = 403,
                isOpen       = true,
                package      = "changpai",
                location     = 4,
                showIndex    = 3,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "jsqp_rudong",
                createName   = "DHJSQP_RDCP_RD",
                cardTheame   = "0|0|1",
            },
            {
                img          = "public/module/setplaymodedata/public_setplaymodedatajiangsu.atlas,JiangSu_Main_图标_海安",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatajiangsu.atlas,海安",
                hallName     = "南通市",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "海安麻将",
                gameName     = "NTHA",
                gameId       = 404,
                isOpen       = true,
                package      = "majiang",
                location     = 4,
                showIndex    = 4,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "jsnthamj_nantong",
                createName   = "DHJSQP_NTHA_HA",
                cardTheame   = "1|1|2",
            }
        },
    },
    {
        id           = 5,
        name         = "扬州市",
        isOpen       = true,
        showIndex    = 5,
        playModeList ={
            {
                img          = "JiangSu_Main_图标_跌到胡",
                headIcon     = "Main_入口_跌倒胡",
                hallName     = "扬州跌倒胡",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "扬州跌倒胡",
                gameName     = "YZDDH",
                gameId       = 501,
                isOpen       = true,
                package      = "majiang",
                location     = 5,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "yzmj_diedaohu",
                createName   = "DHJSQP_YZDDH_DDH",
            }
        },
    }
}
return playModeConfig
