-- 编辑器自动生成，请勿直接修改！
local playModeConfig = {
    {
        id           = 1,
        name         = "大众玩法",
        isOpen       = true,
        showIndex    = 1,
        playModeList ={
            {
                img          = "Public_Electorate_按钮_图标_红中",
                headIcon     = "Main_入口_红中",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "红中麻将",
                gameName     = "HZMJ",
                gameId       = 1,
                isOpen       = false,
                package      = "majiang",
                location     = 1,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "hzmj_v2",
                wanfaType    = "hzmj_v2",
                createName   = "DHAHQP_HZMJ_HZ",
                goldRoomName         = "红中麻将",
                cardTheame   = "0|0|1",
            },
            {
                img          = "Public_Electorate_按钮_图标_比鸡",
                headIcon     = "Main_入口_极速比鸡",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "BiJi_Main_入口_图标_",
                tag          = 3,
                name         = "欢乐比鸡",
                gameName     = "BIJI",
                gameId       = 2,
                isOpen       = false,
                package      = "biji",
                location     = 1,
                showIndex    = 2,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "0|1|2",
                createName   = "DHAHQP_BIJI_BJ",
                tips         = "欢乐比鸡|舒城比鸡|六人比鸡",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_极速跑得快",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "Public_Main_入口_图标_",
                tag          = 1,
                name         = "极速跑得快",
                gameName     = "RUNFAST",
                gameId       = 3,
                isOpen       = false,
                package      = "runfast",
                location     = 1,
                showIndex    = 3,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = true,
                playTypeName = "pdk_3",
                wanfaType    = "1|2",
                createName   = "DHAHQP_RUNFAST_RUNFAST",
                tips         = "安徽关牌|经典跑得快",
                goldRoomName         = "跑得快",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_拼十",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "Public_Main_入口_图标_",
                tag          = 3,
                name         = "极速牛仔",
                gameName     = "BULLFIGHT",
                gameId       = 4,
                isOpen       = false,
                package      = "cowboy",
                location     = 1,
                showIndex    = 4,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                playTypeName = "bullfight",
                wanfaType    = "0|1|2|3",
                createName   = "DHAHQP_BULLFIGHT_BF",
                tips         = "轮流坐庄|随机坐庄|看牌抢庄|炸金牛",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_飘三叶",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "Public_Main_入口_图标_",
                tag          = 0,
                name         = "欢乐掼蛋",
                gameName     = "GUANDAN",
                gameId       = 5,
                isOpen       = false,
                package      = "guandan",
                location     = 1,
                showIndex    = 5,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "0|1",
                createName   = "DHAHQP_GUANDAN_GD",
                tips         = "团团转|经典玩法",
            },
            {
                img          = "Public_Electorate_按钮_图标_通用斗地主",
                headIcon     = "Main_入口_斗地主",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 1,
                name         = "斗地主",
                gameName     = "DOUDIZHU",
                gameId       = 7,
                isOpen       = false,
                package      = "doudizhu",
                location     = 1,
                showIndex    = 6,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "0",
                createName   = "DHAHQP_DOUDIZHU_DOUDIZHU",
                tips         = "斗地主",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_飘三叶",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "Public_Main_入口_图标_",
                tag          = 3,
                name         = "飘三叶",
                gameName     = "ZHAJINHUA",
                gameId       = 6,
                isOpen       = false,
                package      = "zhajinhua",
                location     = 1,
                showIndex    = 7,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "0",
                createName   = "DHAHQP_ZHAJINHUA_ZHAJINHUA",
                tips         = "飘三叶",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_扑克通用",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "Public_Main_入口_图标_",
                tag          = 0,
                name         = "逮狗腿",
                gameName     = "DAIGOUTUI",
                gameId       = 8,
                isOpen       = false,
                package      = "daigoutui",
                location     = 1,
                showIndex    = 8,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "0",
                createName   = "DHAHQP_DAIGOUTUI_DAIGOUTUI",
                tips         = "逮狗腿",
            },
            {
                img          = "Public_Electorate_按钮_图标_红中",
                headIcon     = "Main_入口_换换",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "换换麻将",
                gameName     = "DZHH",
                gameId       = 9,
                isOpen       = false,
                package      = "majiang",
                location     = 1,
                showIndex    = 9,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "wbmj_huanhuan",
                wanfaType    = "wbmj_huanhuan",
                createName   = "DHAHQP_DZHH_HH",
                tips         = "换换",
                goldRoomName         = "换换麻将",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_飘三叶",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 3,
                name         = "十三张",
                gameName     = "SHISANZHANG",
                gameId       = 10,
                isOpen       = false,
                package      = "shisanzhang",
                location     = 1,
                showIndex    = 10,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "0",
                createName   = "DHAHQP_SHISANZHANG_SSZ",
            },
            {
                img          = "public/module/setplaymodedata/public_setplaymodedatapublic.atlas,更多玩法 叫家子",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatapublic.atlas,推荐玩法-叫家子",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "叫家子",
                gameName     = "JIAOJIAZI",
                gameId       = 11,
                isOpen       = false,
                package      = "jiaojiazi",
                location     = 1,
                showIndex    = 11,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "1|2",
                createName   = "DHAHQP_JIAOJIAZI_JIAOJIAZI",
                tips         = "安庆三副|安庆二副",
            }
        },
    },
    {
        id           = 2,
        name         = "营口市",
        isOpen       = true,
        showIndex    = 2,
        playModeList ={
            {
                img          = "public/module/setplaymodedata/public_setplaymodedataliaoning.atlas,Main_营口",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedataliaoning.atlas,营口",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "营口麻将",
                gameName     = "YKMJ",
                gameId       = 201,
                isOpen       = true,
                package      = "majiang",
                location     = 2,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "lnmj_yingkou",
                createName   = "DHLNQP_YKMJ_YK",
                cardTheame   = "1|1|2",
            }
        },
    }
}
return playModeConfig
