-- 编辑器自动生成，请勿直接修改！
local playModeConfig = {
    {
        id           = 1,
        name         = "大众玩法",
        isOpen       = true,
        showIndex    = 1,
        playModeList ={
            {
                img          = "Public_Electorate_按钮_图标_红中",
                headIcon     = "Main_入口_红中",
                hallName     = "红中麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "红中麻将",
                gameName     = "ZYHZ",
                gameId       = 1,
                isOpen       = true,
                package      = "majiang",
                location     = 1,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "sxmj_zyhz",
                createName   = "DHSXQP_ZYHZ_HZ",
                cardTheame   = "0|0|1",
            }
        },
    },
    {
        id           = 2,
        name         = "西安市",
        isOpen       = false,
        showIndex    = 2,
        playModeList ={
            {
                img          = "Public_Electorate_按钮_图标_红中",
                headIcon     = "",
                hallName     = "陕西麻将",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "陕西麻将",
                gameName     = "SXSX",
                gameId       = 203,
                isOpen       = true,
                package      = "majiang",
                location     = 2,
                showIndex    = 1,
                isOnline     = false,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "sxmj_shanxi",
                createName   = "DHSXQP_SXSX_SX",
            },
            {
                img          = "Public_Electorate_按钮_图标_红中",
                headIcon     = "",
                hallName     = "西安市",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "西安麻将",
                gameName     = "SXXA",
                gameId       = 201,
                isOpen       = true,
                package      = "majiang",
                location     = 2,
                showIndex    = 2,
                isOnline     = false,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "sxmj_xian",
                createName   = "DHSXQP_SXXA_XA",
            },
            {
                img          = "Public_Electorate_按钮_图标_红中",
                headIcon     = "",
                hallName     = "西安市",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "渭南麻将",
                gameName     = "SXWN",
                gameId       = 202,
                isOpen       = true,
                package      = "majiang",
                location     = 2,
                showIndex    = 3,
                isOnline     = false,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "sxmj_weinan",
                createName   = "DHSXQP_SXWN_WN",
            }
        },
    }
}
return playModeConfig
