-- 编辑器自动生成，请勿直接修改！
local playModeConfig = {
    {
        id           = 2,
        name         = "大众玩法",
        isOpen       = true,
        showIndex    = 1,
        playModeList ={
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_极速跑得快",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 1,
                name         = "跑得快",
                gameName     = "RUNFAST",
                gameId       = 201,
                isOpen       = true,
                package      = "runfast",
                location     = 2,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = true,
                playTypeName = "pdk_3",
                wanfaType    = "2",
                createName   = "DHSCQP_RUNFAST_RUNFAST",
                tips         = "跑得快",
                goldRoomName         = "跑得快",
            },
            {
                img          = "Public_Electorate_按钮_图标_通用斗地主",
                headIcon     = "Main_入口_斗地主",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 1,
                name         = "斗地主",
                gameName     = "DOUDIZHU",
                gameId       = 202,
                isOpen       = true,
                package      = "doudizhu",
                location     = 2,
                showIndex    = 2,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "0",
                createName   = "DHSCQP_DOUDIZHU_DOUDIZHU",
                tips         = "斗地主",
            }
        },
    },
    {
        id           = 1,
        name         = "眉山市",
        isOpen       = true,
        showIndex    = 2,
        playModeList ={
            {
                img          = "public/module/setplaymodedata/public_setplaymodedatasichuan.atlas,四川_眉山_仁寿",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatasichuan.atlas,四川_眉山_仁寿_大",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "仁寿血战",
                gameName     = "RSXZ",
                gameId       = 1,
                isOpen       = true,
                package      = "majiang",
                location     = 1,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "dhscqp_rsxz",
                createName   = "DHSCQP_RSXZ_RS",
                cardTheame   = "2|2|3",
            }
        },
    }
}
return playModeConfig
