-- 编辑器自动生成，请勿直接修改！
local playModeConfig = {
    {
        id           = 1,
        name         = "大众玩法",
        isOpen       = true,
        showIndex    = 1,
        playModeList ={
            {
                img          = "XinJiang_Main_图标_杠上花",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedataxinjiang.atlas,新疆杠上花",
                hallName     = "新疆杠上花",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "新疆杠上花",
                gameName     = "XJGSH",
                gameId       = 1,
                isOpen       = true,
                package      = "majiang",
                location     = 1,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "xjmj_gangshanghua",
                createName   = "DHXJQP_XJGSH_GSH",
                cardTheame   = "0|0|1",
            },
            {
                img          = "XinJiang_Main_图标_血战",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedataxinjiang.atlas,新疆血战到底",
                hallName     = "血战到底",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "血战到底",
                gameName     = "XZDD",
                gameId       = 2,
                isOpen       = true,
                package      = "majiang",
                location     = 1,
                showIndex    = 2,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "xjmj_xuezhan",
                createName   = "DHXJQP_XZDD_XZ",
            },
            {
                img          = "Public_Electorate_按钮_图标_通用斗地主",
                headIcon     = "Main_入口_斗地主",
                hallName     = "斗地主",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 1,
                name         = "斗地主",
                gameName     = "DOUDIZHU",
                gameId       = 3,
                isOpen       = true,
                package      = "doudizhu",
                location     = 1,
                showIndex    = 3,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "0",
                createName   = "DHXJQP_DOUDIZHU_DOUDIZHU",
                tips         = "斗地主",
            }
        },
    }
}
return playModeConfig
