-- 编辑器自动生成，请勿直接修改！
local playModeConfig = {
    {
        id           = 1,
        name         = "大众玩法",
        isOpen       = true,
        showIndex    = 1,
        playModeList ={
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_极速跑得快",
                hallName     = "跑得快",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 1,
                name         = "跑得快",
                gameName     = "RUNFAST",
                gameId       = 1,
                isOpen       = true,
                package      = "runfast",
                location     = 1,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = true,
                playTypeName = "pdk_3",
                wanfaType    = "2",
                createName   = "DHYNQP_RUNFAST_RUNFAST",
                tips         = "跑得快",
                goldRoomName         = "跑得快",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_拼十",
                hallName     = "拼十",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 3,
                name         = "拼十",
                gameName     = "BULLFIGHT",
                gameId       = 2,
                isOpen       = false,
                package      = "cowboy",
                location     = 1,
                showIndex    = 2,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                playTypeName = "bullfight",
                wanfaType    = "0|1|2|3",
                createName   = "DHYNQP_BULLFIGHT_BF",
                tips         = "轮流坐庄|随机坐庄|看牌抢庄|炸金牛",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_飘三叶",
                hallName     = "叼三批",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 3,
                name         = "叼三批",
                gameName     = "ZHAJINHUA",
                gameId       = 4,
                isOpen       = false,
                package      = "zhajinhua",
                location     = 1,
                showIndex    = 3,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "0",
                createName   = "DHYNQP_ZHAJINHUA_ZHAJINHUA",
                tips         = "叼三批",
            },
            {
                img          = "Public_Electorate_按钮_图标_扑克通用",
                headIcon     = "Main_入口_飘三叶",
                hallName     = "捞腌菜",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "捞腌菜",
                gameName     = "LAOYANCAI",
                gameId       = 3,
                isOpen       = false,
                package      = "laoyancai",
                location     = 1,
                showIndex    = 4,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "0|1",
                createName   = "DHYNQP_LAOYANCAI_LAOYANCAI",
                tips         = "经典玩法|码宝轮庄",
            },
            {
                img          = "Public_Electorate_按钮_图标_通用斗地主",
                headIcon     = "Main_入口_斗地主",
                hallName     = "斗地主",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 1,
                name         = "斗地主",
                gameName     = "DOUDIZHU",
                gameId       = 5,
                isOpen       = true,
                package      = "doudizhu",
                location     = 1,
                showIndex    = 5,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "0",
                createName   = "DHYNQP_DOUDIZHU_DOUDIZHU",
                tips         = "斗地主",
            }
        },
    },
    {
        id           = 2,
        name         = "文山州",
        isOpen       = true,
        showIndex    = 2,
        playModeList ={
            {
                img          = "YunNan_Main_图标_山",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatayunnan.atlas,砚山麻将",
                hallName     = "文山州",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "砚山麻将",
                gameName     = "WSZMJ",
                gameId       = 201,
                isOpen       = true,
                package      = "majiang",
                location     = 2,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "ynwsz_yanshan",
                createName   = "DHYNQP_WSZMJ_YS",
                cardTheame   = "0|0|1",
            }
        },
    },
    {
        id           = 3,
        name         = "曲靖市",
        isOpen       = true,
        showIndex    = 3,
        playModeList ={
            {
                img          = "YunNan_Main_图标_曲靖飞小鸡",
                headIcon     = "Main_入口_飞小鸡",
                hallName     = "飞小鸡",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "飞小鸡",
                gameName     = "QJMJFXJ",
                gameId       = 301,
                isOpen       = true,
                package      = "majiang",
                location     = 3,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "ynqj_feixiaoji",
                wanfaType    = "ynqj_feixiaoji",
                createName   = "DHYNQP_QJMJFXJ_FXJ",
                goldRoomName         = "飞小鸡",
                cardTheame   = "1|1|2",
            }
        },
    },
    {
        id           = 4,
        name         = "楚雄州",
        isOpen       = true,
        showIndex    = 4,
        playModeList ={
            {
                img          = "public/module/setplaymodedata/public_setplaymodedatayunnan.atlas,YunNan_Main_图标_楚雄",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatayunnan.atlas,楚雄",
                hallName     = "楚雄四五筒",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "楚雄四五筒",
                gameName     = "CXSWT",
                gameId       = 401,
                isOpen       = true,
                package      = "majiang",
                location     = 4,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "dhynqp_cxswt",
                wanfaType    = "dhynqp_cxswt",
                createName   = "DHYNQP_CXSWT_SWT",
                goldRoomName         = "楚雄四五筒",
                cardTheame   = "1|0|1",
            }
        },
    },
    {
        id           = 5,
        name         = "玉溪市",
        isOpen       = true,
        showIndex    = 5,
        playModeList ={
            {
                img          = "public/module/setplaymodedata/public_setplaymodedatayunnan.atlas,YunNan_Main_图标_玉溪",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatayunnan.atlas,玉溪",
                hallName     = "玉溪五六筒",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "玉溪五六筒",
                gameName     = "YXWLT",
                gameId       = 501,
                isOpen       = true,
                package      = "majiang",
                location     = 5,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "dhynqp_yxwlt",
                wanfaType    = "dhynqp_yxwlt",
                createName   = "DHYNQP_YXWLT_WLT",
                goldRoomName         = "玉溪五六筒",
                cardTheame   = "1|0|1",
            },
            {
                img          = "public/module/setplaymodedata/public_setplaymodedatayunnan.atlas,YunNan_Main_图标_玉溪",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatayunnan.atlas,玉溪",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "玉溪小鸡飞",
                gameName     = "YXXJF",
                gameId       = 502,
                isOpen       = true,
                package      = "majiang",
                location     = 5,
                showIndex    = 2,
                isOnline     = true,
                isOpenGold   = true,
                isOpenMatch   = false,
                playTypeName = "dhynqp_yxxjf",
                wanfaType    = "dhynqp_yxxjf",
                createName   = "DHYNQP_YXXJF_YJX",
                goldRoomName         = "玉溪小鸡飞",
                cardTheame   = "1|0|1",
            }
        },
    },
    {
        id           = 6,
        name         = "德宏州",
        isOpen       = true,
        showIndex    = 6,
        playModeList ={
            {
                img          = "public/module/setplaymodedata/public_setplaymodedatayunnan.atlas,YunNan_Main_图标_德宏",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatayunnan.atlas,Main_入口_德宏",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "德宏麻将",
                gameName     = "DHMJ",
                gameId       = 601,
                isOpen       = true,
                package      = "majiang",
                location     = 6,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "ynmj_dehong",
                createName   = "DHYNQP_DHMJ_DH",
                cardTheame   = "1|1|2",
            }
        },
    },
    {
        id           = 7,
        name         = "保山市",
        isOpen       = true,
        showIndex    = 7,
        playModeList ={
            {
                img          = "public/module/setplaymodedata/public_setplaymodedatayunnan.atlas,YunNan_Main_图标_保山",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatayunnan.atlas,Main_入口_保山",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "保山麻将",
                gameName     = "BSMJ",
                gameId       = 701,
                isOpen       = true,
                package      = "majiang",
                location     = 7,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "ynmj_baoshan",
                createName   = "DHYNQP_BSMJ_BS",
                cardTheame   = "1|1|2",
            }
        },
    },
    {
        id           = 8,
        name         = "昆明市",
        isOpen       = true,
        showIndex    = 8,
        playModeList ={
            {
                img          = "public/module/setplaymodedata/public_setplaymodedatayunnan.atlas,YunNan_Main_图标_昆明",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatayunnan.atlas,云南_昆明",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "昆明麻将",
                gameName     = "KMMJ",
                gameId       = 801,
                isOpen       = true,
                package      = "majiang",
                location     = 8,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "dhynqp_kmmj",
                createName   = "DHYNQP_KMMJ_KM",
                cardTheame   = "1|1|2",
            },
            {
                img          = "Public_Electorate_按钮_图标_红中",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedataxinjiang.atlas,新疆血战到底",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "昆明血战",
                gameName     = "KMXZDD",
                gameId       = 802,
                isOpen       = true,
                package      = "majiang",
                location     = 8,
                showIndex    = 2,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "dhynqp_kmxzdd",
                createName   = "DHYNQP_KMXZDD_XZ",
                cardTheame   = "1|1|2",
            }
        },
    },
    {
        id           = 9,
        name         = "临沧市",
        isOpen       = true,
        showIndex    = 9,
        playModeList ={
            {
                img          = "Public_Electorate_按钮_图标_红中",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatayunnan.atlas,云南_临沧",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "临沧麻将",
                gameName     = "LCMJ",
                gameId       = 901,
                isOpen       = true,
                package      = "majiang",
                location     = 9,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "dhynqp_lcmj",
                createName   = "DHYNQP_LCMJ_LC",
                cardTheame   = "1|1|2",
            }
        },
    },
    {
        id           = 10,
        name         = "普洱市",
        isOpen       = true,
        showIndex    = 10,
        playModeList ={
            {
                img          = "public/module/setplaymodedata/public_setplaymodedatayunnan.atlas,YunNan_Main_图标_普洱",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatayunnan.atlas,云南_普洱",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "普洱麻将",
                gameName     = "PEMJ",
                gameId       = 1001,
                isOpen       = true,
                package      = "majiang",
                location     = 10,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "dhynqp_pemj",
                createName   = "DHYNQP_PEMJ_PE",
                cardTheame   = "1|1|2",
            },
            {
                img          = "public/module/setplaymodedata/public_setplaymodedatayunnan.atlas,YunNan_Main_图标_卡二条",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatayunnan.atlas,云南_卡二条",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "普洱卡二条",
                gameName     = "PEKET",
                gameId       = 1002,
                isOpen       = true,
                package      = "majiang",
                location     = 10,
                showIndex    = 2,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "dhynqp_peket",
                createName   = "DHYNQP_PEKET_KET",
                cardTheame   = "1|1|2",
            }
        },
    },
    {
        id           = 11,
        name         = "丽江市",
        isOpen       = true,
        showIndex    = 11,
        playModeList ={
            {
                img          = "public/module/setplaymodedata/public_setplaymodedatayunnan.atlas,YunNan_Main_图标_卡心五",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatayunnan.atlas,云南_卡心五",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "丽江卡心五",
                gameName     = "HZMJ",
                gameId       = 1101,
                isOpen       = true,
                package      = "majiang",
                location     = 11,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "LJKXW",
                createName   = "DHYNQP_LJKXW_KXW",
                cardTheame   = "1|1|2",
            }
        },
    },
    {
        id           = 12,
        name         = "昭通市",
        isOpen       = true,
        showIndex    = 12,
        playModeList ={
            {
                img          = "Public_Electorate_按钮_图标_红中",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatayunnan.atlas,云南_昭通",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "昭通麻将",
                gameName     = "ZTMJ",
                gameId       = 1201,
                isOpen       = true,
                package      = "majiang",
                location     = 12,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "dhynqp_ztmj",
                createName   = "DHYNQP_ZTMJ_ZT",
                cardTheame   = "1|1|2",
            }
        },
    },
    {
        id           = 13,
        name         = "大理市",
        isOpen       = true,
        showIndex    = 13,
        playModeList ={
            {
                img          = "Public_Electorate_按钮_图标_红中",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatayunnan.atlas,云南_大理",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "大理麻将",
                gameName     = "DLMJ",
                gameId       = 1301,
                isOpen       = true,
                package      = "majiang",
                location     = 13,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "dhynqp_dlmj",
                createName   = "DHYNQP_DLMJ_DL",
                cardTheame   = "1|1|2",
            }
        },
    },
    {
        id           = 14,
        name         = "红河州",
        isOpen       = true,
        showIndex    = 14,
        playModeList ={
            {
                img          = "public/module/setplaymodedata/public_setplaymodedatayunnan.atlas,YunNan_Main_图标_个旧",
                headIcon     = "public/module/setplaymodedata/public_setplaymodedatayunnan.atlas,云南_个旧",
                hallName     = "",
                bg           = "BackgroundHongZhong",
                btnImg       = "HongZhong_Main_入口_图标_",
                tag          = 0,
                name         = "个旧麻将",
                gameName     = "HHGJ",
                gameId       = 1401,
                isOpen       = false,
                package      = "majiang",
                location     = 14,
                showIndex    = 1,
                isOnline     = true,
                isOpenGold   = false,
                isOpenMatch   = false,
                wanfaType    = "dhynqp_hhgj",
                createName   = "DHYNQP_HHGJ_GJ",
                cardTheame   = "1|1|2",
            }
        },
    }
}
return playModeConfig
