//auto generated by editor 9/29/2018 12:33:34 PM







#ifndef ConfigInfo_h
#define ConfigInfo_h
// Bugly
const static NSString *Bugly_APPID = @"b84a162675";
// 高德Key
const static NSString *AMapServices_Key = @"81987ec501f3f6a8f7ee78febd4e01e9";
// 魔窗
const static NSString *MW_APIKey = @"CSCGRV553M3AQQ5EZM4FT7UVCFMINVDC";

const static NSString *XIANLIAO_APPID = @"eNaWBnQnErlT2akM";

const static NSString *LIAOBEI_APPID = @"lbOKNaVz7RECkN";

// TalkingData
const static NSString *TalkingData_APPID = @"CA0E977CC1564F44A3B5F762EE471D3F";
const static NSString *Channel = @"ios_none";

// 极光推送
const static NSString *JiGuang_APIKey = @"1480dd0d2e49fb7330971888";


const static BOOL *JiGuang_IsKaiFa = FALSE;



// HTTPDNS 
const static int HTTPDNS_AccountID =181184;

const static NSString  *HTTPDNS_PreResolveHosts[6] =   {@"api.dhahqp.sincebest.com",@"vip.dhahqp.sincebest.com",@"api.dhgdqp.sincebest.com",@"vip.dhgdqp.sincebest.com",@"api.dhjsqp.sincebest.com",@"vip.dhjsqp.sincebest.com",};

const static NSString *HTTPDNS_ExpiredIPEnabled = @"true";


#endif
//auto generated by editor end 9/29/2018 12:33:34 PM=
