---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by chenz.
--- DateTime: 2018/7/18 12:01
---
local ModuleCache = ModuleCache
local SwitchGameConfig = {}
SwitchGameConfig.gameConfig = {
    {
        regionName = "曲靖市",
        name = "跑得快",
        gameName = "HAOCAI_RUNFAST",
        desc = "15/16张、非/必压、3A带1算炸多种玩法皆可选择。",
        open = true,
        gameId = "RUNFAST",
        poker = true,
        gold = true,
        match = false,
    },
    {
        regionName = "曲靖市",
        name = "斗地主",
        gameName = "HAOCAI_DOUDIZHU",
        desc = "经典斗地主玩法，简单又刺激。",
        open = true,
        gameId = "DOUDIZHU",
        poker = true,
        gold = false,
        match = false,
    },
    {
        regionName = "大理市",
        name = "大理跑得快",
        gameName = "HAOCAI_RUNFASTDL",
        desc = "5人玩法的跑得快，10张牌，上手简单，节奏快",
        open = true,
        gameId = "RUNFASTDL",
        poker = true,
        gold = false,
        match = false,
    },
    {
        regionName = "大理市",
        name = "大理推倒胡",
        gameName = "HAOCAI_DLTDH",
        desc = "大理地方特色推倒胡玩法，个性鲜明，趣味十足！",
        open = true,
        gameId = "DLTDH",
        poker = false,
        gold = false,
        match = false,
    },
    {
        regionName = "大理市",
        name = "大理血战",
        gameName = "HAOCAI_DLXZDD",
        desc = "定缺换张查大叫，门清中张金钩钓。",
        open = true,
        gameId = "DLXZDD",
        poker = false,
        gold = false,
        match = false,
    },
    {
        regionName = "曲靖市",
        name = "飞小鸡",
        gameName = "HAOCAI_QJMJFXJ",
        desc = "十风、四赖、十三幺，地道曲靖飞小鸡，小鸡归为胡翻她。",
        open = true,
        gameId = "QJMJFXJ",
        poker = false,
        gold = true,
        match = false,
    },
}

if ModuleCache.GameManager.developmentMode then
    for _, v in ipairs(SwitchGameConfig.gameConfig) do
        v.open = true
    end
end

function SwitchGameConfig.gameNameGetPointConfig(gameName)
    for _, v in ipairs(SwitchGameConfig.gameConfig) do
        if v.open and v.gameName == gameName then
            return v
        end
    end
    return nil
end

function SwitchGameConfig.gameIds()
    local str = ""
    for _, v in ipairs(SwitchGameConfig.gameConfig) do
        if v.open then
            if str == "" then
                str = str .. v.gameName
            else
                str = str .. "," .. v.gameName
            end
        end
    end
    return str
end

function SwitchGameConfig.pokerGoldList()
    local pokerNames = {}
    for _, v in ipairs(SwitchGameConfig.gameConfig) do
        if v.open and v.poker and v.gold then
            table.insert(pokerNames, v)
        end
    end
    return pokerNames
end

function SwitchGameConfig.majongGoldList()
    local majongs = {}
    for _, v in ipairs(SwitchGameConfig.gameConfig) do
        if v.open and not v.poker and v.gold then
            table.insert(majongs, v)
        end
    end
    return majongs
end

function SwitchGameConfig.majongList()
    local majongs = {}
    for _, v in ipairs(SwitchGameConfig.gameConfig) do
        if v.open and not v.poker then
            table.insert(majongs, v)
        end
    end
    return majongs
end

--根据游戏名字获取对应的信息
function  SwitchGameConfig.get_region_by_name(name)
    local curGame = nil
    for _, v in ipairs(SwitchGameConfig.gameConfig) do
        curGame = v
        if v.open and v.name == name then
            break
        end
    end
    return curGame
end
--通过省份获取poker or 麻将列表
function SwitchGameConfig.get_gamelist_by_regionname(regionname)
    local pokersDatas = {}
    local majiangDatas = {}
    local curGameName  = ModuleCache.AppData.get_real_app_and_game_name()
    for _, v in ipairs(SwitchGameConfig.gameConfig) do
        if (v.open == true) and v.regionName == regionname then
            if v.poker then
                if curGameName == v.gameName then
                    table.insert(pokersDatas, 1, v)
                else
                    table.insert(pokersDatas, v)
                end 
            else
                if curGameName == v.gameName then
                    table.insert(majiangDatas, 1, v)
                else
                    table.insert(majiangDatas, v)
                end
            end 
        end
    end
    return pokersDatas, majiangDatas
end

function SwitchGameConfig.get_region_list()
    local regionData = {}
    for _, v in ipairs(SwitchGameConfig.gameConfig) do
        if v.regionName then
            regionData[v.regionName] = regionData[v.regionName] or {}
            table.insert(regionData[v.regionName], v)
        end 
    end
    return regionData
end



return SwitchGameConfig