D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=D:\Project\Client\dhqpyx\Public\probuff\baibazhang\table  --plugin=protoc-gen-lua="D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=D:\Project\Client\dhqpyx\Public\out_lua_pb\baibazhang\table D:\Project\Client\dhqpyx\Public\probuff\baibazhang\table\room.proto
D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=D:\Project\Client\dhqpyx\Public\probuff\biji  --plugin=protoc-gen-lua="D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=D:\Project\Client\dhqpyx\Public\out_lua_pb\biji D:\Project\Client\dhqpyx\Public\probuff\biji\login.proto
D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=D:\Project\Client\dhqpyx\Public\probuff\biji\bijitable  --plugin=protoc-gen-lua="D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=D:\Project\Client\dhqpyx\Public\out_lua_pb\biji\bijitable D:\Project\Client\dhqpyx\Public\probuff\biji\bijitable\room.proto
D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=D:\Project\Client\dhqpyx\Public\probuff\biji\table  --plugin=protoc-gen-lua="D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=D:\Project\Client\dhqpyx\Public\out_lua_pb\biji\table D:\Project\Client\dhqpyx\Public\probuff\biji\table\game.proto
D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=D:\Project\Client\dhqpyx\Public\probuff\biji\table  --plugin=protoc-gen-lua="D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=D:\Project\Client\dhqpyx\Public\out_lua_pb\biji\table D:\Project\Client\dhqpyx\Public\probuff\biji\table\login.proto
D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=D:\Project\Client\dhqpyx\Public\probuff\biji\table  --plugin=protoc-gen-lua="D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=D:\Project\Client\dhqpyx\Public\out_lua_pb\biji\table D:\Project\Client\dhqpyx\Public\probuff\biji\table\room.proto
D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=D:\Project\Client\dhqpyx\Public\probuff\changpai  --plugin=protoc-gen-lua="D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=D:\Project\Client\dhqpyx\Public\out_lua_pb\changpai D:\Project\Client\dhqpyx\Public\probuff\changpai\Game.proto
D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=D:\Project\Client\dhqpyx\Public\probuff\cowboy  --plugin=protoc-gen-lua="D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=D:\Project\Client\dhqpyx\Public\out_lua_pb\cowboy D:\Project\Client\dhqpyx\Public\probuff\cowboy\login.proto
D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=D:\Project\Client\dhqpyx\Public\probuff\cowboy\table  --plugin=protoc-gen-lua="D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=D:\Project\Client\dhqpyx\Public\out_lua_pb\cowboy\table D:\Project\Client\dhqpyx\Public\probuff\cowboy\table\game.proto
D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=D:\Project\Client\dhqpyx\Public\probuff\cowboy\table  --plugin=protoc-gen-lua="D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=D:\Project\Client\dhqpyx\Public\out_lua_pb\cowboy\table D:\Project\Client\dhqpyx\Public\probuff\cowboy\table\login.proto
D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=D:\Project\Client\dhqpyx\Public\probuff\cowboy\table  --plugin=protoc-gen-lua="D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=D:\Project\Client\dhqpyx\Public\out_lua_pb\cowboy\table D:\Project\Client\dhqpyx\Public\probuff\cowboy\table\room.proto
D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=D:\Project\Client\dhqpyx\Public\probuff\daigoutui\table  --plugin=protoc-gen-lua="D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=D:\Project\Client\dhqpyx\Public\out_lua_pb\daigoutui\table D:\Project\Client\dhqpyx\Public\probuff\daigoutui\table\game.proto
D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=D:\Project\Client\dhqpyx\Public\probuff\doudizhu\table  --plugin=protoc-gen-lua="D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=D:\Project\Client\dhqpyx\Public\out_lua_pb\doudizhu\table D:\Project\Client\dhqpyx\Public\probuff\doudizhu\table\game.proto
D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=D:\Project\Client\dhqpyx\Public\probuff\guandan  --plugin=protoc-gen-lua="D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=D:\Project\Client\dhqpyx\Public\out_lua_pb\guandan D:\Project\Client\dhqpyx\Public\probuff\guandan\login.proto
D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=D:\Project\Client\dhqpyx\Public\probuff\guandan\table  --plugin=protoc-gen-lua="D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=D:\Project\Client\dhqpyx\Public\out_lua_pb\guandan\table D:\Project\Client\dhqpyx\Public\probuff\guandan\table\game_guandan.proto
D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=D:\Project\Client\dhqpyx\Public\probuff\guandan\table  --plugin=protoc-gen-lua="D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=D:\Project\Client\dhqpyx\Public\out_lua_pb\guandan\table D:\Project\Client\dhqpyx\Public\probuff\guandan\table\login.proto
D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=D:\Project\Client\dhqpyx\Public\probuff\guandan\table  --plugin=protoc-gen-lua="D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=D:\Project\Client\dhqpyx\Public\out_lua_pb\guandan\table D:\Project\Client\dhqpyx\Public\probuff\guandan\table\room.proto
D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=D:\Project\Client\dhqpyx\Public\probuff\henanmj  --plugin=protoc-gen-lua="D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=D:\Project\Client\dhqpyx\Public\out_lua_pb\henanmj D:\Project\Client\dhqpyx\Public\probuff\henanmj\Game.proto
D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=D:\Project\Client\dhqpyx\Public\probuff\henanmj  --plugin=protoc-gen-lua="D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=D:\Project\Client\dhqpyx\Public\out_lua_pb\henanmj D:\Project\Client\dhqpyx\Public\probuff\henanmj\GameFrame.proto
D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=D:\Project\Client\dhqpyx\Public\probuff\henanmj  --plugin=protoc-gen-lua="D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=D:\Project\Client\dhqpyx\Public\out_lua_pb\henanmj D:\Project\Client\dhqpyx\Public\probuff\henanmj\Login.proto
D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=D:\Project\Client\dhqpyx\Public\probuff\laoyancai\table  --plugin=protoc-gen-lua="D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=D:\Project\Client\dhqpyx\Public\out_lua_pb\laoyancai\table D:\Project\Client\dhqpyx\Public\probuff\laoyancai\table\game.proto
D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=D:\Project\Client\dhqpyx\Public\probuff\paohuzi  --plugin=protoc-gen-lua="D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=D:\Project\Client\dhqpyx\Public\out_lua_pb\paohuzi D:\Project\Client\dhqpyx\Public\probuff\paohuzi\GameCommon.proto
D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=D:\Project\Client\dhqpyx\Public\probuff\paohuzi  --plugin=protoc-gen-lua="D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=D:\Project\Client\dhqpyx\Public\out_lua_pb\paohuzi D:\Project\Client\dhqpyx\Public\probuff\paohuzi\GamePaoHuZi.proto
D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=D:\Project\Client\dhqpyx\Public\probuff\public  --plugin=protoc-gen-lua="D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=D:\Project\Client\dhqpyx\Public\out_lua_pb\public D:\Project\Client\dhqpyx\Public\probuff\public\login.proto
D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=D:\Project\Client\dhqpyx\Public\probuff\public\skynet_table  --plugin=protoc-gen-lua="D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=D:\Project\Client\dhqpyx\Public\out_lua_pb\public\skynet_table D:\Project\Client\dhqpyx\Public\probuff\public\skynet_table\login.proto
D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=D:\Project\Client\dhqpyx\Public\probuff\public\skynet_table  --plugin=protoc-gen-lua="D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=D:\Project\Client\dhqpyx\Public\out_lua_pb\public\skynet_table D:\Project\Client\dhqpyx\Public\probuff\public\skynet_table\room.proto
D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=D:\Project\Client\dhqpyx\Public\probuff\runfast  --plugin=protoc-gen-lua="D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=D:\Project\Client\dhqpyx\Public\out_lua_pb\runfast D:\Project\Client\dhqpyx\Public\probuff\runfast\login.proto
D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=D:\Project\Client\dhqpyx\Public\probuff\runfast\mytable  --plugin=protoc-gen-lua="D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=D:\Project\Client\dhqpyx\Public\out_lua_pb\runfast\mytable D:\Project\Client\dhqpyx\Public\probuff\runfast\mytable\game.proto
D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=D:\Project\Client\dhqpyx\Public\probuff\runfast\table  --plugin=protoc-gen-lua="D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=D:\Project\Client\dhqpyx\Public\out_lua_pb\runfast\table D:\Project\Client\dhqpyx\Public\probuff\runfast\table\login.proto
D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=D:\Project\Client\dhqpyx\Public\probuff\runfast\table  --plugin=protoc-gen-lua="D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=D:\Project\Client\dhqpyx\Public\out_lua_pb\runfast\table D:\Project\Client\dhqpyx\Public\probuff\runfast\table\room.proto
D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=D:\Project\Client\dhqpyx\Public\probuff\sangong\table  --plugin=protoc-gen-lua="D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=D:\Project\Client\dhqpyx\Public\out_lua_pb\sangong\table D:\Project\Client\dhqpyx\Public\probuff\sangong\table\game.proto
D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=D:\Project\Client\dhqpyx\Public\probuff\shisanzhang\table  --plugin=protoc-gen-lua="D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=D:\Project\Client\dhqpyx\Public\out_lua_pb\shisanzhang\table D:\Project\Client\dhqpyx\Public\probuff\shisanzhang\table\room.proto
D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=D:\Project\Client\dhqpyx\Public\probuff\wushik  --plugin=protoc-gen-lua="D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=D:\Project\Client\dhqpyx\Public\out_lua_pb\wushik D:\Project\Client\dhqpyx\Public\probuff\wushik\game.proto
D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=D:\Project\Client\dhqpyx\Public\probuff\zhajinhua\mytable  --plugin=protoc-gen-lua="D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=D:\Project\Client\dhqpyx\Public\out_lua_pb\zhajinhua\mytable D:\Project\Client\dhqpyx\Public\probuff\zhajinhua\mytable\game.proto
D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\example\protoc.exe --proto_path=D:\Project\Client\dhqpyx\Public\probuff\zhajinhua\mytable  --plugin=protoc-gen-lua="D:\Project\Client\dhqpyx\Public\client\protoc-gen-lua\plugin\build.bat" --lua_out=D:\Project\Client\dhqpyx\Public\out_lua_pb\zhajinhua\mytable D:\Project\Client\dhqpyx\Public\probuff\zhajinhua\mytable\room.proto
